# **DeBERTa**

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1" # "0" o "1"

In [2]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cuda

In [3]:
from utils import *

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, classification_report, confusion_matrix
from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
)

/home/n.emmolo/miniconda3/envs/env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-11-08 15:44:26.801921: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-08 15:44:26.863938: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-08 15:44:28.157898: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [4]:
# Ignore warnings for cleaner output
import warnings
warnings.filterwarnings("ignore")

In [5]:
# --------------------
# Build model function
# --------------------

def build_model(learning_rate=2e-5, weight_decay=0.1):
    """
    Builds a DeBERTa model (microsoft/deberta-base) for sequence classification.

    Args:
        learning_rate (float): Learning rate for the optimizer.
        weight_decay (float): Weight decay for AdamW optimizer.

    Returns:
        model (AutoModelForSequenceClassification): HuggingFace DeBERTa model.
        tokenizer (AutoTokenizer): Tokenizer associated with the model.
        train_args (TrainingArguments): Default training configuration.
    """

    model = AutoModelForSequenceClassification.from_pretrained("microsoft/deberta-base", num_labels=2)
    tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

    train_args = TrainingArguments(
        output_dir="./deberta_finetune_output",
        eval_strategy="epoch",
        save_strategy="no",
        learning_rate=learning_rate,
        weight_decay=weight_decay,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        logging_dir="./logs",
        load_best_model_at_end=False,
        logging_steps=50,
        seed=42,
    )

    return model, tokenizer, train_args

In [6]:
# ----------------------
# Tokenization functions
# ----------------------

def tokenize_function(examples, tokenizer, max_len=128):
    """
    Tokenizes the input examples using the provided tokenizer.

    Args:
        examples (dict): A dictionary containing the text data to be tokenized.
        tokenizer (AutoTokenizer): The tokenizer to use for tokenization.
        max_len (int): Maximum length for padding/truncation.

    Returns:
        dict: Tokenized inputs with padding and truncation applied.
    """

    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=max_len,
    )


def tokenize_datasets(datasets, tokenizer):
    """
    Tokenizes multiple datasets using the provided tokenizer.

    Args:
        datasets (dict): A dictionary where keys are dataset names and values are dictionaries with 'train', 'val', and 'test' splits.
        tokenizer (AutoTokenizer): The tokenizer to use for tokenization.

    Returns:
        dict: A dictionary with the same keys as input datasets, but with tokenized datasets.
    """

    tokenized_datasets = {}
    
    for name, data in datasets.items():
        print(f"\n=== Tokenizing dataset: {name} ===")

        train_dataset = Dataset.from_dict({"text": data["train"][0], "label": data["train"][1].astype(int)})
        val_dataset = Dataset.from_dict({"text": data["val"][0], "label": data["val"][1].astype(int)})
        test_dataset = Dataset.from_dict({"text": data["test"][0], "label": data["test"][1].astype(int)})

        train_tokenized = train_dataset.map(lambda x: tokenize_function(x, tokenizer), batched=True)
        val_tokenized = val_dataset.map(lambda x: tokenize_function(x, tokenizer), batched=True)
        test_tokenized = test_dataset.map(lambda x: tokenize_function(x, tokenizer), batched=True)

        tokenized_datasets[name] = {
            "train": (train_tokenized, np.array(train_dataset["label"])),
            "val": (val_tokenized, np.array(val_dataset["label"])),
            "test": (test_tokenized, np.array(test_dataset["label"]))
        }

    return tokenized_datasets

## VERSION 1: Dataset (Simple)

In [7]:
dataset_df = data_loading() # load all datasets

for name, df in dataset_df.items():
    print(f"Name: {name}, Number of samples: {len(df)}")

# dataset_df = dict(list(dataset_df.items())[:5])

print("\nSplitting datasets into train/val/test...")
datasets = {name: split_dataset(df) for name, df in dataset_df.items()} # split all datasets in train/val/test

model, tokenizer, train_args = build_model()

print("\nComputing tokenized datasets...")
datasets =  tokenize_datasets(datasets, tokenizer) # tokenize all datasets

Name: Celebrity, Number of samples: 500
Name: CIDII, Number of samples: 722
Name: FaKES, Number of samples: 842
Name: FakeVsSatire, Number of samples: 486
Name: Horne, Number of samples: 326
Name: Infodemic, Number of samples: 10559
Name: ISOT, Number of samples: 44271
Name: Kaggle_clement, Number of samples: 39105
Name: Kaggle_meg, Number of samples: 12845
Name: LIAR_PLUS, Number of samples: 12784
Name: Politifact, Number of samples: 504
Name: Unipi_NDF, Number of samples: 554

Splitting datasets into train/val/test...

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Computing tokenized datasets...

=== Tokenizing dataset: Celebrity ===

Map: 100%|███████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 1493.62 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1861.42 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1893.22 examples/s]

=== Tokenizing dataset: CIDII ===

Map: 100%|███████████████████████████████████████████████████████████████| 433/433 [00:00<00:00, 5498.44 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 144/144 [00:00<00:00, 3864.23 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 145/145 [00:00<00:00, 2997.97 examples/s]

=== Tokenizing dataset: FaKES ===

Map: 100%|███████████████████████████████████████████████████████████████| 505/505 [00:00<00:00, 3536.25 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 168/168 [00:00<00:00, 2864.45 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 169/169 [00:00<00:00, 2873.99 examples/s]

=== Tokenizing dataset: FakeVsSatire ===

Map: 100%|███████████████████████████████████████████████████████████████| 291/291 [00:00<00:00, 1902.92 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████| 97/97 [00:00<00:00, 1594.97 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 1687.83 examples/s]

=== Tokenizing dataset: Horne ===

Map: 100%|███████████████████████████████████████████████████████████████| 195/195 [00:00<00:00, 1399.14 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 65/65 [00:00<00:00, 999.64 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 66/66 [00:00<00:00, 922.31 examples/s]

=== Tokenizing dataset: Infodemic ===

Map: 100%|█████████████████████████████████████████████████████████████| 6335/6335 [00:00<00:00, 9986.80 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 9506.87 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 10025.51 examples/s]

=== Tokenizing dataset: ISOT ===

Map: 100%|███████████████████████████████████████████████████████████| 26562/26562 [00:09<00:00, 2689.48 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 8854/8854 [00:03<00:00, 2448.79 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 8855/8855 [00:03<00:00, 2723.50 examples/s]

=== Tokenizing dataset: Kaggle_clement ===

Map: 100%|███████████████████████████████████████████████████████████| 23463/23463 [00:08<00:00, 2732.96 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 7821/7821 [00:03<00:00, 2487.45 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 7821/7821 [00:02<00:00, 2830.78 examples/s]

=== Tokenizing dataset: Kaggle_meg ===

Map: 100%|█████████████████████████████████████████████████████████████| 7707/7707 [00:04<00:00, 1749.10 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 1791.57 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 1580.12 examples/s]

=== Tokenizing dataset: LIAR_PLUS ===

Map: 100%|█████████████████████████████████████████████████████████████| 7670/7670 [00:00<00:00, 7792.21 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2557/2557 [00:00<00:00, 11549.45 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2557/2557 [00:00<00:00, 11629.67 examples/s]

=== Tokenizing dataset: Politifact ===

Map: 100%|████████████████████████████████████████████████████████████████| 302/302 [00:00<00:00, 978.49 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 799.74 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 785.23 examples/s]

=== Tokenizing dataset: Unipi_NDF ===

Map: 100%|███████████████████████████████████████████████████████████████| 332/332 [00:00<00:00, 5428.10 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 3890.85 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 3758.22 examples/s]

In [8]:
# --------------------------------
# Fine-tuning on multiple datasets
# --------------------------------

results = {}

for i, (name, data) in enumerate(datasets.items()):
    print(f"\n=== Phase {i+1}: Fine-tuning on {name} ===")

    X_train, y_train = data["train"]
    X_val, y_val = data["val"]
    X_test, y_test = data["test"]

    # define trainer
    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=X_train,
        eval_dataset=X_val,
    )

    # fine-tune on train + val
    trainer.train()

    # evaluate on current dataset
    y_pred = trainer.predict(X_test)
    y_pred = np.argmax(y_pred.predictions, axis=1)
    print(f"\nClassification Report after {name}:")
    print(classification_report(y_test, y_pred))
    print(f"Confusion Matrix after {name}:")
    print(confusion_matrix(y_test, y_pred))
    print(f"Weighted F1-score after {name}: {f1_score(y_test, y_pred, average='weighted'):.4f}")

    # evaluate on all datasets
    print("\n--- Evaluation on all datasets ---")
    results[name] = {}
    for test_name, test_data in datasets.items():
        X_te, y_te = test_data["test"]
        preds = trainer.predict(X_te)
        preds = np.argmax(preds.predictions, axis=1)
        f1 = f1_score(y_te, preds, average="weighted")
        results[name][test_name] = f1
        print(f"Evaluation on {test_name}: Weighted F1 = {f1:.4f}")

=== Phase 1: Fine-tuning on Celebrity ===

Classification Report after Celebrity:
              precision    recall  f1-score   support

           0       0.74      0.86      0.80        50
           1       0.83      0.70      0.76        50

    accuracy                           0.78       100
   macro avg       0.79      0.78      0.78       100
weighted avg       0.79      0.78      0.78       100

Confusion Matrix after Celebrity:
[[43  7]
 [15 35]]
Weighted F1-score after Celebrity: 0.7786

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.7786

Evaluation on CIDII: Weighted F1 = 0.8288

Evaluation on FaKES: Weighted F1 = 0.4325

Evaluation on FakeVsSatire: Weighted F1 = 0.6363

Evaluation on Horne: Weighted F1 = 0.6390

Evaluation on Infodemic: Weighted F1 = 0.3982

Evaluation on ISOT: Weighted F1 = 0.7367

Evaluation on Kaggle_clement: Weighted F1 = 0.9157

Evaluation on Kaggle_meg: Weighted F1 = 0.3936

Evaluation on LIAR_PLUS: Weighted F1 = 0.4752

Evaluation on Politifact: Weighted F1 = 0.6983

Evaluation on Unipi_NDF: Weighted F1 = 0.6190

=== Phase 2: Fine-tuning on CIDII ===

Classification Report after CIDII:
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        85
           1       1.00      0.92      0.96        60

    accuracy                           0.97       145
   macro avg       0.97      0.96      0.96       145
weighted avg       0.97      0.97      0.97       145

Confusion Matrix after CIDII:
[[85  0]
 [ 5 55]]
Weighted F1-score after CIDII: 0.9653

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3552

Evaluation on CIDII: Weighted F1 = 0.9653

Evaluation on FaKES: Weighted F1 = 0.3388

Evaluation on FakeVsSatire: Weighted F1 = 0.4278

Evaluation on Horne: Weighted F1 = 0.5500

Evaluation on Infodemic: Weighted F1 = 0.3072

Evaluation on ISOT: Weighted F1 = 0.9232

Evaluation on Kaggle_clement: Weighted F1 = 0.5403

Evaluation on Kaggle_meg: Weighted F1 = 0.0102

Evaluation on LIAR_PLUS: Weighted F1 = 0.2836

Evaluation on Politifact: Weighted F1 = 0.6248

Evaluation on Unipi_NDF: Weighted F1 = 0.2355

=== Phase 3: Fine-tuning on FaKES ===

Classification Report after FaKES:
              precision    recall  f1-score   support

           0       0.50      0.67      0.57        89
           1       0.40      0.24      0.30        80

    accuracy                           0.47       169
   macro avg       0.45      0.46      0.43       169
weighted avg       0.45      0.47      0.44       169

Confusion Matrix after FaKES:
[[60 29]
 [61 19]]
Weighted F1-score after FaKES: 0.4415

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.7768

Evaluation on CIDII: Weighted F1 = 0.9441

Evaluation on FaKES: Weighted F1 = 0.4415

Evaluation on FakeVsSatire: Weighted F1 = 0.3104

Evaluation on Horne: Weighted F1 = 0.5710

Evaluation on Infodemic: Weighted F1 = 0.7072

Evaluation on ISOT: Weighted F1 = 0.8144

Evaluation on Kaggle_clement: Weighted F1 = 0.6796

Evaluation on Kaggle_meg: Weighted F1 = 0.7942

Evaluation on LIAR_PLUS: Weighted F1 = 0.4650

Evaluation on Politifact: Weighted F1 = 0.5877

Evaluation on Unipi_NDF: Weighted F1 = 0.6396

=== Phase 4: Fine-tuning on FakeVsSatire ===

Classification Report after FakeVsSatire:
              precision    recall  f1-score   support

           0       0.94      0.71      0.81        41
           1       0.82      0.96      0.89        57

    accuracy                           0.86        98
   macro avg       0.88      0.84      0.85        98
weighted avg       0.87      0.86      0.85        98

Confusion Matrix after FakeVsSatire:
[[29 12]
 [ 2 55]]
Weighted F1-score after FakeVsSatire: 0.8530

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.7100

Evaluation on CIDII: Weighted F1 = 0.9724

Evaluation on FaKES: Weighted F1 = 0.4958

Evaluation on FakeVsSatire: Weighted F1 = 0.8530

Evaluation on Horne: Weighted F1 = 0.7016

Evaluation on Infodemic: Weighted F1 = 0.5171

Evaluation on ISOT: Weighted F1 = 0.8908

Evaluation on Kaggle_clement: Weighted F1 = 0.9885

Evaluation on Kaggle_meg: Weighted F1 = 0.4373

Evaluation on LIAR_PLUS: Weighted F1 = 0.5040

Evaluation on Politifact: Weighted F1 = 0.7905

Evaluation on Unipi_NDF: Weighted F1 = 0.5425

=== Phase 5: Fine-tuning on Horne ===

Classification Report after Horne:
              precision    recall  f1-score   support

           0       0.80      0.95      0.87        41
           1       0.88      0.60      0.71        25

    accuracy                           0.82        66
   macro avg       0.84      0.78      0.79        66
weighted avg       0.83      0.82      0.81        66

Confusion Matrix after Horne:
[[39  2]
 [10 15]]
Weighted F1-score after Horne: 0.8089

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.7399

Evaluation on CIDII: Weighted F1 = 0.9226

Evaluation on FaKES: Weighted F1 = 0.5090

Evaluation on FakeVsSatire: Weighted F1 = 0.7552

Evaluation on Horne: Weighted F1 = 0.8089

Evaluation on Infodemic: Weighted F1 = 0.4429

Evaluation on ISOT: Weighted F1 = 0.9349

Evaluation on Kaggle_clement: Weighted F1 = 0.9844

Evaluation on Kaggle_meg: Weighted F1 = 0.4295

Evaluation on LIAR_PLUS: Weighted F1 = 0.5297

Evaluation on Politifact: Weighted F1 = 0.7591

Evaluation on Unipi_NDF: Weighted F1 = 0.4795

=== Phase 6: Fine-tuning on Infodemic ===

Classification Report after Infodemic:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      1106
           1       0.99      0.98      0.98      1006

    accuracy                           0.98      2112
   macro avg       0.98      0.98      0.98      2112
weighted avg       0.98      0.98      0.98      2112

Confusion Matrix after Infodemic:
[[1093   13]
 [  23  983]]
Weighted F1-score after Infodemic: 0.9830

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3333

Evaluation on CIDII: Weighted F1 = 0.4258

Evaluation on FaKES: Weighted F1 = 0.4344

Evaluation on FakeVsSatire: Weighted F1 = 0.4278

Evaluation on Horne: Weighted F1 = 0.2081

Evaluation on Infodemic: Weighted F1 = 0.9830

Evaluation on ISOT: Weighted F1 = 0.3548

Evaluation on Kaggle_clement: Weighted F1 = 0.2924

Evaluation on Kaggle_meg: Weighted F1 = 0.0087

Evaluation on LIAR_PLUS: Weighted F1 = 0.2818

Evaluation on Politifact: Weighted F1 = 0.3705

Evaluation on Unipi_NDF: Weighted F1 = 0.3884

=== Phase 7: Fine-tuning on ISOT ===

Classification Report after ISOT:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4284
           1       1.00      1.00      1.00      4571

    accuracy                           1.00      8855
   macro avg       1.00      1.00      1.00      8855
weighted avg       1.00      1.00      1.00      8855

Confusion Matrix after ISOT:
[[4284    0]
 [   1 4570]]
Weighted F1-score after ISOT: 0.9999

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3552

Evaluation on CIDII: Weighted F1 = 0.5982

Evaluation on FaKES: Weighted F1 = 0.3782

Evaluation on FakeVsSatire: Weighted F1 = 0.5012

Evaluation on Horne: Weighted F1 = 0.4759

Evaluation on Infodemic: Weighted F1 = 0.3239

Evaluation on ISOT: Weighted F1 = 0.9999

Evaluation on Kaggle_clement: Weighted F1 = 0.8895

Evaluation on Kaggle_meg: Weighted F1 = 0.0427

Evaluation on LIAR_PLUS: Weighted F1 = 0.2713

Evaluation on Politifact: Weighted F1 = 0.4836

Evaluation on Unipi_NDF: Weighted F1 = 0.3199

=== Phase 8: Fine-tuning on Kaggle_clement ===

Classification Report after Kaggle_clement:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4240
           1       1.00      1.00      1.00      3581

    accuracy                           1.00      7821
   macro avg       1.00      1.00      1.00      7821
weighted avg       1.00      1.00      1.00      7821

Confusion Matrix after Kaggle_clement:
[[4239    1]
 [   0 3581]]
Weighted F1-score after Kaggle_clement: 0.9999

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.4107

Evaluation on CIDII: Weighted F1 = 0.7658

Evaluation on FaKES: Weighted F1 = 0.4913

Evaluation on FakeVsSatire: Weighted F1 = 0.4933

Evaluation on Horne: Weighted F1 = 0.6107

Evaluation on Infodemic: Weighted F1 = 0.6035

Evaluation on ISOT: Weighted F1 = 0.9879

Evaluation on Kaggle_clement: Weighted F1 = 0.9999

Evaluation on Kaggle_meg: Weighted F1 = 0.1472

Evaluation on LIAR_PLUS: Weighted F1 = 0.5444

Evaluation on Politifact: Weighted F1 = 0.5154

Evaluation on Unipi_NDF: Weighted F1 = 0.3561

=== Phase 9: Fine-tuning on Kaggle_meg ===

Classification Report after Kaggle_meg:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2514
           1       0.47      0.15      0.22        55

    accuracy                           0.98      2569
   macro avg       0.73      0.57      0.61      2569
weighted avg       0.97      0.98      0.97      2569

Confusion Matrix after Kaggle_meg:
[[2505    9]
 [  47    8]]
Weighted F1-score after Kaggle_meg: 0.9725

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3197

Evaluation on CIDII: Weighted F1 = 0.4333

Evaluation on FaKES: Weighted F1 = 0.3633

Evaluation on FakeVsSatire: Weighted F1 = 0.2468

Evaluation on Horne: Weighted F1 = 0.4621

Evaluation on Infodemic: Weighted F1 = 0.3600

Evaluation on ISOT: Weighted F1 = 0.2455

Evaluation on Kaggle_clement: Weighted F1 = 0.3012

Evaluation on Kaggle_meg: Weighted F1 = 0.9725

Evaluation on LIAR_PLUS: Weighted F1 = 0.4002

Evaluation on Politifact: Weighted F1 = 0.4996

Evaluation on Unipi_NDF: Weighted F1 = 0.4569

=== Phase 10: Fine-tuning on LIAR_PLUS ===

Classification Report after LIAR_PLUS:
              precision    recall  f1-score   support

           0       0.65      0.76      0.70      1426
           1       0.61      0.48      0.54      1131

    accuracy                           0.64      2557
   macro avg       0.63      0.62      0.62      2557
weighted avg       0.63      0.64      0.63      2557

Confusion Matrix after LIAR_PLUS:
[[1080  346]
 [ 587  544]]
Weighted F1-score after LIAR_PLUS: 0.6276

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.5478

Evaluation on CIDII: Weighted F1 = 0.4712

Evaluation on FaKES: Weighted F1 = 0.4266

Evaluation on FakeVsSatire: Weighted F1 = 0.6502

Evaluation on Horne: Weighted F1 = 0.5020

Evaluation on Infodemic: Weighted F1 = 0.7463

Evaluation on ISOT: Weighted F1 = 0.3124

Evaluation on Kaggle_clement: Weighted F1 = 0.4267

Evaluation on Kaggle_meg: Weighted F1 = 0.6460

Evaluation on LIAR_PLUS: Weighted F1 = 0.6276

Evaluation on Politifact: Weighted F1 = 0.5928

Evaluation on Unipi_NDF: Weighted F1 = 0.4150

=== Phase 11: Fine-tuning on Politifact ===

Classification Report after Politifact:
              precision    recall  f1-score   support

           0       0.83      0.97      0.89        65
           1       0.92      0.64      0.75        36

    accuracy                           0.85       101
   macro avg       0.87      0.80      0.82       101
weighted avg       0.86      0.85      0.84       101

Confusion Matrix after Politifact:
[[63  2]
 [13 23]]
Weighted F1-score after Politifact: 0.8439

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.6588

Evaluation on CIDII: Weighted F1 = 0.5299

Evaluation on FaKES: Weighted F1 = 0.3846

Evaluation on FakeVsSatire: Weighted F1 = 0.6781

Evaluation on Horne: Weighted F1 = 0.5947

Evaluation on Infodemic: Weighted F1 = 0.8199

Evaluation on ISOT: Weighted F1 = 0.7309

Evaluation on Kaggle_clement: Weighted F1 = 0.7560

Evaluation on Kaggle_meg: Weighted F1 = 0.6890

Evaluation on LIAR_PLUS: Weighted F1 = 0.5953

Evaluation on Politifact: Weighted F1 = 0.8439

Evaluation on Unipi_NDF: Weighted F1 = 0.3617

=== Phase 12: Fine-tuning on Unipi_NDF ===

Classification Report after Unipi_NDF:
              precision    recall  f1-score   support

           0       0.84      0.96      0.90        68
           1       0.91      0.72      0.81        43

    accuracy                           0.86       111
   macro avg       0.88      0.84      0.85       111
weighted avg       0.87      0.86      0.86       111

Confusion Matrix after Unipi_NDF:
[[65  3]
 [12 31]]
Weighted F1-score after Unipi_NDF: 0.8612

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.7267

Evaluation on CIDII: Weighted F1 = 0.7448

Evaluation on FaKES: Weighted F1 = 0.4835

Evaluation on FakeVsSatire: Weighted F1 = 0.6874

Evaluation on Horne: Weighted F1 = 0.6053

Evaluation on Infodemic: Weighted F1 = 0.7658

Evaluation on ISOT: Weighted F1 = 0.7463

Evaluation on Kaggle_clement: Weighted F1 = 0.9088

Evaluation on Kaggle_meg: Weighted F1 = 0.5889

Evaluation on LIAR_PLUS: Weighted F1 = 0.5546

Evaluation on Politifact: Weighted F1 = 0.8743

Evaluation on Unipi_NDF: Weighted F1 = 0.8612

In [9]:
# ---------------
# Results summary
# ---------------

print("\n=== Results Summary ===")
for name, res in results.items():
    print(f"\nResults after training on {name}:")
    for test_name, f1 in res.items():
        print(f"  Test on {test_name}: Weighted F1 = {f1:.4f}")

=== Results Summary ===

Results after training on Celebrity:
  Test on Celebrity: Weighted F1 = 0.7786
  Test on CIDII: Weighted F1 = 0.8288
  Test on FaKES: Weighted F1 = 0.4325
  Test on FakeVsSatire: Weighted F1 = 0.6363
  Test on Horne: Weighted F1 = 0.6390
  Test on Infodemic: Weighted F1 = 0.3982
  Test on ISOT: Weighted F1 = 0.7367
  Test on Kaggle_clement: Weighted F1 = 0.9157
  Test on Kaggle_meg: Weighted F1 = 0.3936
  Test on LIAR_PLUS: Weighted F1 = 0.4752
  Test on Politifact: Weighted F1 = 0.6983
  Test on Unipi_NDF: Weighted F1 = 0.6190

Results after training on CIDII:
  Test on Celebrity: Weighted F1 = 0.3552
  Test on CIDII: Weighted F1 = 0.9653
  Test on FaKES: Weighted F1 = 0.3388
  Test on FakeVsSatire: Weighted F1 = 0.4278
  Test on Horne: Weighted F1 = 0.5500
  Test on Infodemic: Weighted F1 = 0.3072
  Test on ISOT: Weighted F1 = 0.9232
  Test on Kaggle_clement: Weighted F1 = 0.5403
  Test on Kaggle_meg: Weighted F1 = 0.0102
  Test on LIAR_PLUS: Weighted F1 = 0.2836
  Test on Politifact: Weighted F1 = 0.6248
  Test on Unipi_NDF: Weighted F1 = 0.2355

Results after training on FaKES:
  Test on Celebrity: Weighted F1 = 0.7768
  Test on CIDII: Weighted F1 = 0.9441
  Test on FaKES: Weighted F1 = 0.4415
  Test on FakeVsSatire: Weighted F1 = 0.3104
  Test on Horne: Weighted F1 = 0.5710
  Test on Infodemic: Weighted F1 = 0.7072
  Test on ISOT: Weighted F1 = 0.8144
  Test on Kaggle_clement: Weighted F1 = 0.6796
  Test on Kaggle_meg: Weighted F1 = 0.7942
  Test on LIAR_PLUS: Weighted F1 = 0.4650
  Test on Politifact: Weighted F1 = 0.5877
  Test on Unipi_NDF: Weighted F1 = 0.6396

Results after training on FakeVsSatire:
  Test on Celebrity: Weighted F1 = 0.7100
  Test on CIDII: Weighted F1 = 0.9724
  Test on FaKES: Weighted F1 = 0.4958
  Test on FakeVsSatire: Weighted F1 = 0.8530
  Test on Horne: Weighted F1 = 0.7016
  Test on Infodemic: Weighted F1 = 0.5171
  Test on ISOT: Weighted F1 = 0.8908
  Test on Kaggle_clement: Weighted F1 = 0.9885
  Test on Kaggle_meg: Weighted F1 = 0.4373
  Test on LIAR_PLUS: Weighted F1 = 0.5040
  Test on Politifact: Weighted F1 = 0.7905
  Test on Unipi_NDF: Weighted F1 = 0.5425

Results after training on Horne:
  Test on Celebrity: Weighted F1 = 0.7399
  Test on CIDII: Weighted F1 = 0.9226
  Test on FaKES: Weighted F1 = 0.5090
  Test on FakeVsSatire: Weighted F1 = 0.7552
  Test on Horne: Weighted F1 = 0.8089
  Test on Infodemic: Weighted F1 = 0.4429
  Test on ISOT: Weighted F1 = 0.9349
  Test on Kaggle_clement: Weighted F1 = 0.9844
  Test on Kaggle_meg: Weighted F1 = 0.4295
  Test on LIAR_PLUS: Weighted F1 = 0.5297
  Test on Politifact: Weighted F1 = 0.7591
  Test on Unipi_NDF: Weighted F1 = 0.4795

Results after training on Infodemic:
  Test on Celebrity: Weighted F1 = 0.3333
  Test on CIDII: Weighted F1 = 0.4258
  Test on FaKES: Weighted F1 = 0.4344
  Test on FakeVsSatire: Weighted F1 = 0.4278
  Test on Horne: Weighted F1 = 0.2081
  Test on Infodemic: Weighted F1 = 0.9830
  Test on ISOT: Weighted F1 = 0.3548
  Test on Kaggle_clement: Weighted F1 = 0.2924
  Test on Kaggle_meg: Weighted F1 = 0.0087
  Test on LIAR_PLUS: Weighted F1 = 0.2818
  Test on Politifact: Weighted F1 = 0.3705
  Test on Unipi_NDF: Weighted F1 = 0.3884

Results after training on ISOT:
  Test on Celebrity: Weighted F1 = 0.3552
  Test on CIDII: Weighted F1 = 0.5982
  Test on FaKES: Weighted F1 = 0.3782
  Test on FakeVsSatire: Weighted F1 = 0.5012
  Test on Horne: Weighted F1 = 0.4759
  Test on Infodemic: Weighted F1 = 0.3239
  Test on ISOT: Weighted F1 = 0.9999
  Test on Kaggle_clement: Weighted F1 = 0.8895
  Test on Kaggle_meg: Weighted F1 = 0.0427
  Test on LIAR_PLUS: Weighted F1 = 0.2713
  Test on Politifact: Weighted F1 = 0.4836
  Test on Unipi_NDF: Weighted F1 = 0.3199

Results after training on Kaggle_clement:
  Test on Celebrity: Weighted F1 = 0.4107
  Test on CIDII: Weighted F1 = 0.7658
  Test on FaKES: Weighted F1 = 0.4913
  Test on FakeVsSatire: Weighted F1 = 0.4933
  Test on Horne: Weighted F1 = 0.6107
  Test on Infodemic: Weighted F1 = 0.6035
  Test on ISOT: Weighted F1 = 0.9879
  Test on Kaggle_clement: Weighted F1 = 0.9999
  Test on Kaggle_meg: Weighted F1 = 0.1472
  Test on LIAR_PLUS: Weighted F1 = 0.5444
  Test on Politifact: Weighted F1 = 0.5154
  Test on Unipi_NDF: Weighted F1 = 0.3561

Results after training on Kaggle_meg:
  Test on Celebrity: Weighted F1 = 0.3197
  Test on CIDII: Weighted F1 = 0.4333
  Test on FaKES: Weighted F1 = 0.3633
  Test on FakeVsSatire: Weighted F1 = 0.2468
  Test on Horne: Weighted F1 = 0.4621
  Test on Infodemic: Weighted F1 = 0.3600
  Test on ISOT: Weighted F1 = 0.2455
  Test on Kaggle_clement: Weighted F1 = 0.3012
  Test on Kaggle_meg: Weighted F1 = 0.9725
  Test on LIAR_PLUS: Weighted F1 = 0.4002
  Test on Politifact: Weighted F1 = 0.4996
  Test on Unipi_NDF: Weighted F1 = 0.4569

Results after training on LIAR_PLUS:
  Test on Celebrity: Weighted F1 = 0.5478
  Test on CIDII: Weighted F1 = 0.4712
  Test on FaKES: Weighted F1 = 0.4266
  Test on FakeVsSatire: Weighted F1 = 0.6502
  Test on Horne: Weighted F1 = 0.5020
  Test on Infodemic: Weighted F1 = 0.7463
  Test on ISOT: Weighted F1 = 0.3124
  Test on Kaggle_clement: Weighted F1 = 0.4267
  Test on Kaggle_meg: Weighted F1 = 0.6460
  Test on LIAR_PLUS: Weighted F1 = 0.6276
  Test on Politifact: Weighted F1 = 0.5928
  Test on Unipi_NDF: Weighted F1 = 0.4150

Results after training on Politifact:
  Test on Celebrity: Weighted F1 = 0.6588
  Test on CIDII: Weighted F1 = 0.5299
  Test on FaKES: Weighted F1 = 0.3846
  Test on FakeVsSatire: Weighted F1 = 0.6781
  Test on Horne: Weighted F1 = 0.5947
  Test on Infodemic: Weighted F1 = 0.8199
  Test on ISOT: Weighted F1 = 0.7309
  Test on Kaggle_clement: Weighted F1 = 0.7560
  Test on Kaggle_meg: Weighted F1 = 0.6890
  Test on LIAR_PLUS: Weighted F1 = 0.5953
  Test on Politifact: Weighted F1 = 0.8439
  Test on Unipi_NDF: Weighted F1 = 0.3617

Results after training on Unipi_NDF:
  Test on Celebrity: Weighted F1 = 0.7267
  Test on CIDII: Weighted F1 = 0.7448
  Test on FaKES: Weighted F1 = 0.4835
  Test on FakeVsSatire: Weighted F1 = 0.6874
  Test on Horne: Weighted F1 = 0.6053
  Test on Infodemic: Weighted F1 = 0.7658
  Test on ISOT: Weighted F1 = 0.7463
  Test on Kaggle_clement: Weighted F1 = 0.9088
  Test on Kaggle_meg: Weighted F1 = 0.5889
  Test on LIAR_PLUS: Weighted F1 = 0.5546
  Test on Politifact: Weighted F1 = 0.8743
  Test on Unipi_NDF: Weighted F1 = 0.8612

## VERSION 2: Dataset by Topic

In [7]:
dataset_df = data_by_topic()

# split "politics" in "politics1" and "politics2"
if "politics" in dataset_df:
    dataset_df["politics1"] = dataset_df["politics"].sample(frac=0.5, random_state=42)
    dataset_df["politics2"] = dataset_df["politics"].drop(dataset_df["politics1"].index)
    # drop original "politics" dataset
    del dataset_df["politics"]
    # put "politics1" and "politics2" at the beginning of the dict
    dataset_df = {"politics1": dataset_df["politics1"], "politics2": dataset_df["politics2"], **dataset_df}

for topic, df in dataset_df.items():
    print(f"Topic: {topic}, Number of samples: {len(df)}")

# dataset_df = dict(list(dataset_df.items())[3:]) # remove first 3 datasets

print("\nSplitting datasets into train/val/test...")
datasets = {topic: split_dataset(df) for topic, df in dataset_df.items()} # split all datasets in train/val/test

model, tokenizer, train_args = build_model()

print("\nComputing tokenized datasets...")
datasets =  tokenize_datasets(datasets, tokenizer) # tokenize all datasets

Topic: politics1, Number of samples: 48738
Topic: politics2, Number of samples: 48738
Topic: general, Number of samples: 12845
Topic: covid, Number of samples: 10559
Topic: syria, Number of samples: 842
Topic: islam, Number of samples: 722
Topic: notredame, Number of samples: 554
Topic: gossip, Number of samples: 500

Splitting datasets into train/val/test...

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Computing tokenized datasets...

=== Tokenizing dataset: politics1 ===

Map: 100%|███████████████████████████████████████████████████████████| 29242/29242 [00:09<00:00, 2932.86 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:03<00:00, 3046.94 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:03<00:00, 2843.11 examples/s]

=== Tokenizing dataset: politics2 ===

Map: 100%|███████████████████████████████████████████████████████████| 29242/29242 [00:09<00:00, 3146.74 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:03<00:00, 2811.21 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:03<00:00, 3149.24 examples/s]

=== Tokenizing dataset: general ===

Map: 100%|█████████████████████████████████████████████████████████████| 7707/7707 [00:04<00:00, 1797.37 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 1813.68 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 1681.04 examples/s]

=== Tokenizing dataset: covid ===

Map: 100%|█████████████████████████████████████████████████████████████| 6335/6335 [00:00<00:00, 6955.23 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 9855.34 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 10264.34 examples/s]

=== Tokenizing dataset: syria ===

Map: 100%|███████████████████████████████████████████████████████████████| 505/505 [00:00<00:00, 3502.10 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 168/168 [00:00<00:00, 3045.58 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 169/169 [00:00<00:00, 3200.30 examples/s]

=== Tokenizing dataset: islam ===

Map: 100%|███████████████████████████████████████████████████████████████| 433/433 [00:00<00:00, 6092.81 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 144/144 [00:00<00:00, 4781.39 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 145/145 [00:00<00:00, 4496.83 examples/s]

=== Tokenizing dataset: notredame ===

Map: 100%|███████████████████████████████████████████████████████████████| 332/332 [00:00<00:00, 6674.67 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 4874.90 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 4855.43 examples/s]

=== Tokenizing dataset: gossip ===

Map: 100%|███████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 1945.62 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 2178.34 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 2238.11 examples/s]

In [8]:
# -------------------------------
# Fine-tuning on Dataset by Topic
# -------------------------------

results = {}

# sequential training
for i, (topic, data) in enumerate(datasets.items()):
    print(f"\n=== Phase {i+1}: Training/Fine-tuning on topic: {topic} ===")

    X_train, y_train = data["train"]
    X_val, y_val = data["val"]
    X_test, y_test = data["test"]

    # define trainer
    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=X_train,
        eval_dataset=X_val,
    )

    # fine-tune on train + val
    trainer.train()

    # evaluate on current dataset
    y_pred = trainer.predict(X_test)
    y_pred = np.argmax(y_pred.predictions, axis=1)
    print(f"\nClassification Report after topic {topic}:")
    print(classification_report(y_test, y_pred))
    print(f"Confusion Matrix after topic {topic}:")
    print(confusion_matrix(y_test, y_pred))
    print(f"Weighted F1-score after topic {topic}:", f1_score(y_test, y_pred, average='weighted'))

    # evaluate on all datasets
    print("\n--- Evaluation on all datasets ---")
    results[topic] = {}
    for test_topic, test_data in datasets.items(): # for each topic
        X_te, y_te = test_data["test"]
        preds = trainer.predict(X_te)
        preds = np.argmax(preds.predictions, axis=1)
        f1 = f1_score(y_te, preds, average="weighted")
        results[topic][test_topic] = f1
        print(f"Evaluation on topic {test_topic}: Weighted F1 = {f1:.4f}")

=== Phase 1: Training/Fine-tuning on topic: politics1 ===

Classification Report after topic politics1:
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      5031
           1       0.96      0.93      0.94      4717

    accuracy                           0.95      9748
   macro avg       0.95      0.95      0.95      9748
weighted avg       0.95      0.95      0.95      9748

Confusion Matrix after topic politics1:
[[4863  168]
 [ 352 4365]]
Weighted F1-score after topic politics1: 0.9466041492905594

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.9466

Evaluation on topic politics2: Weighted F1 = 0.9470

Evaluation on topic general: Weighted F1 = 0.3416

Evaluation on topic covid: Weighted F1 = 0.3986

Evaluation on topic syria: Weighted F1 = 0.5307

Evaluation on topic islam: Weighted F1 = 0.3568

Evaluation on topic notredame: Weighted F1 = 0.2571

Evaluation on topic gossip: Weighted F1 = 0.5746

=== Phase 2: Training/Fine-tuning on topic: politics2 ===

Classification Report after topic politics2:
              precision    recall  f1-score   support

           0       0.94      0.97      0.95      5064
           1       0.96      0.93      0.95      4684

    accuracy                           0.95      9748
   macro avg       0.95      0.95      0.95      9748
weighted avg       0.95      0.95      0.95      9748

Confusion Matrix after topic politics2:
[[4887  177]
 [ 317 4367]]
Weighted F1-score after topic politics2: 0.9492840022153107

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.9473

Evaluation on topic politics2: Weighted F1 = 0.9493

Evaluation on topic general: Weighted F1 = 0.3831

Evaluation on topic covid: Weighted F1 = 0.4735

Evaluation on topic syria: Weighted F1 = 0.5180

Evaluation on topic islam: Weighted F1 = 0.4118

Evaluation on topic notredame: Weighted F1 = 0.3756

Evaluation on topic gossip: Weighted F1 = 0.4615

=== Phase 3: Training/Fine-tuning on topic: general ===

Classification Report after topic general:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2514
           1       0.00      0.00      0.00        55

    accuracy                           0.98      2569
   macro avg       0.49      0.50      0.49      2569
weighted avg       0.96      0.98      0.97      2569

Confusion Matrix after topic general:
[[2514    0]
 [  55    0]]
Weighted F1-score after topic general: 0.9680021644592334

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.3514

Evaluation on topic politics2: Weighted F1 = 0.3552

Evaluation on topic general: Weighted F1 = 0.9680

Evaluation on topic covid: Weighted F1 = 0.3600

Evaluation on topic syria: Weighted F1 = 0.3633

Evaluation on topic islam: Weighted F1 = 0.4333

Evaluation on topic notredame: Weighted F1 = 0.4654

Evaluation on topic gossip: Weighted F1 = 0.3333

=== Phase 4: Training/Fine-tuning on topic: covid ===

Classification Report after topic covid:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1106
           1       0.97      0.98      0.98      1006

    accuracy                           0.98      2112
   macro avg       0.98      0.98      0.98      2112
weighted avg       0.98      0.98      0.98      2112

Confusion Matrix after topic covid:
[[1080   26]
 [  24  982]]
Weighted F1-score after topic covid: 0.9763268000862195

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.3195

Evaluation on topic politics2: Weighted F1 = 0.3153

Evaluation on topic general: Weighted F1 = 0.0032

Evaluation on topic covid: Weighted F1 = 0.9763

Evaluation on topic syria: Weighted F1 = 0.3016

Evaluation on topic islam: Weighted F1 = 0.2422

Evaluation on topic notredame: Weighted F1 = 0.3517

Evaluation on topic gossip: Weighted F1 = 0.3333

=== Phase 5: Training/Fine-tuning on topic: syria ===

Classification Report after topic syria:
              precision    recall  f1-score   support

           0       0.54      0.73      0.62        89
           1       0.50      0.30      0.38        80

    accuracy                           0.53       169
   macro avg       0.52      0.52      0.50       169
weighted avg       0.52      0.53      0.50       169

Confusion Matrix after topic syria:
[[65 24]
 [56 24]]
Weighted F1-score after topic syria: 0.5035221189067344

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.3287

Evaluation on topic politics2: Weighted F1 = 0.3284

Evaluation on topic general: Weighted F1 = 0.0442

Evaluation on topic covid: Weighted F1 = 0.9711

Evaluation on topic syria: Weighted F1 = 0.5035

Evaluation on topic islam: Weighted F1 = 0.2422

Evaluation on topic notredame: Weighted F1 = 0.5419

Evaluation on topic gossip: Weighted F1 = 0.3503

=== Phase 6: Training/Fine-tuning on topic: islam ===

Classification Report after topic islam:
              precision    recall  f1-score   support

           0       0.95      0.98      0.97        85
           1       0.97      0.93      0.95        60

    accuracy                           0.96       145
   macro avg       0.96      0.95      0.96       145
weighted avg       0.96      0.96      0.96       145

Confusion Matrix after topic islam:
[[83  2]
 [ 4 56]]
Weighted F1-score after topic islam: 0.9585105949193319

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.3349

Evaluation on topic politics2: Weighted F1 = 0.3361

Evaluation on topic general: Weighted F1 = 0.1682

Evaluation on topic covid: Weighted F1 = 0.9706

Evaluation on topic syria: Weighted F1 = 0.5039

Evaluation on topic islam: Weighted F1 = 0.9585

Evaluation on topic notredame: Weighted F1 = 0.5566

Evaluation on topic gossip: Weighted F1 = 0.4107

=== Phase 7: Training/Fine-tuning on topic: notredame ===

Classification Report after topic notredame:
              precision    recall  f1-score   support

           0       0.90      0.96      0.93        68
           1       0.92      0.84      0.88        43

    accuracy                           0.91       111
   macro avg       0.91      0.90      0.90       111
weighted avg       0.91      0.91      0.91       111

Confusion Matrix after topic notredame:
[[65  3]
 [ 7 36]]
Weighted F1-score after topic notredame: 0.9089995919264212

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.3377

Evaluation on topic politics2: Weighted F1 = 0.3425

Evaluation on topic general: Weighted F1 = 0.4050

Evaluation on topic covid: Weighted F1 = 0.9376

Evaluation on topic syria: Weighted F1 = 0.4914

Evaluation on topic islam: Weighted F1 = 0.9238

Evaluation on topic notredame: Weighted F1 = 0.9090

Evaluation on topic gossip: Weighted F1 = 0.6339

=== Phase 8: Training/Fine-tuning on topic: gossip ===

Classification Report after topic gossip:
              precision    recall  f1-score   support

           0       0.77      0.86      0.81        50
           1       0.84      0.74      0.79        50

    accuracy                           0.80       100
   macro avg       0.80      0.80      0.80       100
weighted avg       0.80      0.80      0.80       100

Confusion Matrix after topic gossip:
[[43  7]
 [13 37]]
Weighted F1-score after topic gossip: 0.7992773986350863

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.3244

Evaluation on topic politics2: Weighted F1 = 0.3384

Evaluation on topic general: Weighted F1 = 0.6268

Evaluation on topic covid: Weighted F1 = 0.9169

Evaluation on topic syria: Weighted F1 = 0.5014

Evaluation on topic islam: Weighted F1 = 0.7847

Evaluation on topic notredame: Weighted F1 = 0.8699

Evaluation on topic gossip: Weighted F1 = 0.7993

In [9]:
# ---------------
# Results summary
# ---------------

print("\n=== Results Summary ===")
for topic, res in results.items():
    print(f"\nResults after training on topic {topic}:")
    for test_topic, f1 in res.items():
        print(f"  Test on topic {test_topic}: Weighted F1 = {f1:.4f}")

=== Results Summary ===

Results after training on topic politics1:
  Test on topic politics1: Weighted F1 = 0.9466
  Test on topic politics2: Weighted F1 = 0.9470
  Test on topic general: Weighted F1 = 0.3416
  Test on topic covid: Weighted F1 = 0.3986
  Test on topic syria: Weighted F1 = 0.5307
  Test on topic islam: Weighted F1 = 0.3568
  Test on topic notredame: Weighted F1 = 0.2571
  Test on topic gossip: Weighted F1 = 0.5746

Results after training on topic politics2:
  Test on topic politics1: Weighted F1 = 0.9473
  Test on topic politics2: Weighted F1 = 0.9493
  Test on topic general: Weighted F1 = 0.3831
  Test on topic covid: Weighted F1 = 0.4735
  Test on topic syria: Weighted F1 = 0.5180
  Test on topic islam: Weighted F1 = 0.4118
  Test on topic notredame: Weighted F1 = 0.3756
  Test on topic gossip: Weighted F1 = 0.4615

Results after training on topic general:
  Test on topic politics1: Weighted F1 = 0.3514
  Test on topic politics2: Weighted F1 = 0.3552
  Test on topic general: Weighted F1 = 0.9680
  Test on topic covid: Weighted F1 = 0.3600
  Test on topic syria: Weighted F1 = 0.3633
  Test on topic islam: Weighted F1 = 0.4333
  Test on topic notredame: Weighted F1 = 0.4654
  Test on topic gossip: Weighted F1 = 0.3333

Results after training on topic covid:
  Test on topic politics1: Weighted F1 = 0.3195
  Test on topic politics2: Weighted F1 = 0.3153
  Test on topic general: Weighted F1 = 0.0032
  Test on topic covid: Weighted F1 = 0.9763
  Test on topic syria: Weighted F1 = 0.3016
  Test on topic islam: Weighted F1 = 0.2422
  Test on topic notredame: Weighted F1 = 0.3517
  Test on topic gossip: Weighted F1 = 0.3333

Results after training on topic syria:
  Test on topic politics1: Weighted F1 = 0.3287
  Test on topic politics2: Weighted F1 = 0.3284
  Test on topic general: Weighted F1 = 0.0442
  Test on topic covid: Weighted F1 = 0.9711
  Test on topic syria: Weighted F1 = 0.5035
  Test on topic islam: Weighted F1 = 0.2422
  Test on topic notredame: Weighted F1 = 0.5419
  Test on topic gossip: Weighted F1 = 0.3503

Results after training on topic islam:
  Test on topic politics1: Weighted F1 = 0.3349
  Test on topic politics2: Weighted F1 = 0.3361
  Test on topic general: Weighted F1 = 0.1682
  Test on topic covid: Weighted F1 = 0.9706
  Test on topic syria: Weighted F1 = 0.5039
  Test on topic islam: Weighted F1 = 0.9585
  Test on topic notredame: Weighted F1 = 0.5566
  Test on topic gossip: Weighted F1 = 0.4107

Results after training on topic notredame:
  Test on topic politics1: Weighted F1 = 0.3377
  Test on topic politics2: Weighted F1 = 0.3425
  Test on topic general: Weighted F1 = 0.4050
  Test on topic covid: Weighted F1 = 0.9376
  Test on topic syria: Weighted F1 = 0.4914
  Test on topic islam: Weighted F1 = 0.9238
  Test on topic notredame: Weighted F1 = 0.9090
  Test on topic gossip: Weighted F1 = 0.6339

Results after training on topic gossip:
  Test on topic politics1: Weighted F1 = 0.3244
  Test on topic politics2: Weighted F1 = 0.3384
  Test on topic general: Weighted F1 = 0.6268
  Test on topic covid: Weighted F1 = 0.9169
  Test on topic syria: Weighted F1 = 0.5014
  Test on topic islam: Weighted F1 = 0.7847
  Test on topic notredame: Weighted F1 = 0.8699
  Test on topic gossip: Weighted F1 = 0.7993

## VERSION 3: Dataset by Date

In [7]:
dataset_df = data_by_date()

for date, df in dataset_df.items():
    print(f"Date: {date}, Number of samples: {len(df)}")

# dataset_df = dict(list(dataset_df.items())[:3]) # remove last 3 datasets

print("\nSplitting datasets into train/val/test...")
datasets = {date: split_dataset(df) for date, df in dataset_df.items()} # split all datasets in train/val/test

model, tokenizer, train_args = build_model()

print("\nComputing tokenized datasets...")
datasets =  tokenize_datasets(datasets, tokenizer) # tokenize all datasets

Date: 2011-2013, Number of samples: 55
Date: 2014, Number of samples: 114
Date: 2015, Number of samples: 84
Date: 2016, Number of samples: 63018
Date: 2017, Number of samples: 16657
Date: 2019, Number of samples: 554
Date: 2020, Number of samples: 10559

Splitting datasets into train/val/test...

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Computing tokenized datasets...

=== Tokenizing dataset: 2011-2013 ===

Map: 100%|██████████████████████████████████████████████████████████████████| 33/33 [00:00<00:00, 877.28 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 464.90 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 480.23 examples/s]

=== Tokenizing dataset: 2014 ===

Map: 100%|█████████████████████████████████████████████████████████████████| 68/68 [00:00<00:00, 2152.79 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 992.91 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 1207.31 examples/s]

=== Tokenizing dataset: 2015 ===

Map: 100%|█████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 1489.26 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 599.61 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 862.61 examples/s]

=== Tokenizing dataset: 2016 ===

Map: 100%|███████████████████████████████████████████████████████████| 37810/37810 [00:16<00:00, 2342.37 examples/s]
Map: 100%|███████████████████████████████████████████████████████████| 12604/12604 [00:05<00:00, 2371.42 examples/s]
Map: 100%|███████████████████████████████████████████████████████████| 12604/12604 [00:04<00:00, 2625.74 examples/s]

=== Tokenizing dataset: 2017 ===

Map: 100%|█████████████████████████████████████████████████████████████| 9994/9994 [00:03<00:00, 3208.84 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 3331/3331 [00:01<00:00, 2449.64 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 3332/3332 [00:01<00:00, 3092.70 examples/s]

=== Tokenizing dataset: 2019 ===

Map: 100%|███████████████████████████████████████████████████████████████| 332/332 [00:00<00:00, 5794.56 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 2737.31 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 3167.82 examples/s]

=== Tokenizing dataset: 2020 ===

Map: 100%|█████████████████████████████████████████████████████████████| 6335/6335 [00:00<00:00, 9730.48 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 9462.52 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 9961.89 examples/s]

In [8]:
# ------------------------------
# Fine-tuning on Dataset by Date
# ------------------------------

results = {}

# sequential training
for i, (date, data) in enumerate(datasets.items()):
    print(f"\n=== Phase {i+1}: Training/Fine-tuning on date: {date} ===")
    
    X_train, y_train = data["train"]
    X_val, y_val = data["val"]
    X_test, y_test = data["test"]

    # define trainer
    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=X_train,
        eval_dataset=X_val,
    )
    
    # fine-tune on train + val
    trainer.train()

    # evaluate on current dataset
    y_pred = trainer.predict(X_test)
    y_pred = np.argmax(y_pred.predictions, axis=1)
    print(f"\nClassification Report after date {date}:")
    print(classification_report(y_test, y_pred))
    print(f"Confusion Matrix after date {date}:")
    print(confusion_matrix(y_test, y_pred))
    print(f"Weighted F1-score after date {date}:", f1_score(y_test, y_pred, average='weighted'))

    # evaluate on all datasets
    print("\n--- Evaluation on all datasets ---")
    results[date] = {}
    for test_date, test_data in datasets.items(): # for each date
        X_te, y_te = test_data["test"]
        preds = trainer.predict(X_te)
        preds = np.argmax(preds.predictions, axis=1)
        f1 = f1_score(y_te, preds, average="weighted")
        results[date][test_date] = f1
        print(f"Evaluation on date {test_date}: Weighted F1 = {f1:.4f}")

=== Phase 1: Training/Fine-tuning on date: 2011-2013 ===

Classification Report after date 2011-2013:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.55      1.00      0.71         6

    accuracy                           0.55        11
   macro avg       0.27      0.50      0.35        11
weighted avg       0.30      0.55      0.39        11

Confusion Matrix after date 2011-2013:
[[0 5]
 [0 6]]
Weighted F1-score after date 2011-2013: 0.3850267379679144

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.3850

Evaluation on date 2014: Weighted F1 = 0.3095

Evaluation on date 2015: Weighted F1 = 0.3665

Evaluation on date 2016: Weighted F1 = 0.2058

Evaluation on date 2017: Weighted F1 = 0.0000

Evaluation on date 2019: Weighted F1 = 0.2163

Evaluation on date 2020: Weighted F1 = 0.3074

=== Phase 2: Training/Fine-tuning on date: 2014 ===

Classification Report after date 2014:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        12
           1       0.48      1.00      0.65        11

    accuracy                           0.48        23
   macro avg       0.24      0.50      0.32        23
weighted avg       0.23      0.48      0.31        23

Confusion Matrix after date 2014:
[[ 0 12]
 [ 0 11]]
Weighted F1-score after date 2014: 0.309462915601023

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.3850

Evaluation on date 2014: Weighted F1 = 0.3095

Evaluation on date 2015: Weighted F1 = 0.3665

Evaluation on date 2016: Weighted F1 = 0.2058

Evaluation on date 2017: Weighted F1 = 0.0000

Evaluation on date 2019: Weighted F1 = 0.2163

Evaluation on date 2020: Weighted F1 = 0.3074

=== Phase 3: Training/Fine-tuning on date: 2015 ===

Classification Report after date 2015:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.53      1.00      0.69         9

    accuracy                           0.53        17
   macro avg       0.26      0.50      0.35        17
weighted avg       0.28      0.53      0.37        17

Confusion Matrix after date 2015:
[[0 8]
 [0 9]]
Weighted F1-score after date 2015: 0.36651583710407243

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.3850

Evaluation on date 2014: Weighted F1 = 0.3095

Evaluation on date 2015: Weighted F1 = 0.3665

Evaluation on date 2016: Weighted F1 = 0.2058

Evaluation on date 2017: Weighted F1 = 0.0000

Evaluation on date 2019: Weighted F1 = 0.2163

Evaluation on date 2020: Weighted F1 = 0.3074

=== Phase 4: Training/Fine-tuning on date: 2016 ===

Classification Report after date 2016:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7861
           1       0.99      0.98      0.98      4743

    accuracy                           0.99     12604
   macro avg       0.99      0.99      0.99     12604
weighted avg       0.99      0.99      0.99     12604

Confusion Matrix after date 2016:
[[7810   51]
 [  91 4652]]
Weighted F1-score after date 2016: 0.9887241767548158

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.4455

Evaluation on date 2014: Weighted F1 = 0.3944

Evaluation on date 2015: Weighted F1 = 0.3055

Evaluation on date 2016: Weighted F1 = 0.9887

Evaluation on date 2017: Weighted F1 = 0.9952

Evaluation on date 2019: Weighted F1 = 0.2373

Evaluation on date 2020: Weighted F1 = 0.4730

=== Phase 5: Training/Fine-tuning on date: 2017 ===

Classification Report after date 2017:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3318
           1       0.55      0.43      0.48        14

    accuracy                           1.00      3332
   macro avg       0.77      0.71      0.74      3332
weighted avg       1.00      1.00      1.00      3332

Confusion Matrix after date 2017:
[[3313    5]
 [   8    6]]
Weighted F1-score after date 2017: 0.9958652272476999

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.4455

Evaluation on date 2014: Weighted F1 = 0.4004

Evaluation on date 2015: Weighted F1 = 0.5092

Evaluation on date 2016: Weighted F1 = 0.6445

Evaluation on date 2017: Weighted F1 = 0.9959

Evaluation on date 2019: Weighted F1 = 0.4612

Evaluation on date 2020: Weighted F1 = 0.4118

=== Phase 6: Training/Fine-tuning on date: 2019 ===

Classification Report after date 2019:
              precision    recall  f1-score   support

           0       0.75      0.82      0.78        68
           1       0.67      0.56      0.61        43

    accuracy                           0.72       111
   macro avg       0.71      0.69      0.70       111
weighted avg       0.72      0.72      0.72       111

Confusion Matrix after date 2019:
[[56 12]
 [19 24]]
Weighted F1-score after date 2019: 0.7151830949299304

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.4935

Evaluation on date 2014: Weighted F1 = 0.3991

Evaluation on date 2015: Weighted F1 = 0.3388

Evaluation on date 2016: Weighted F1 = 0.9482

Evaluation on date 2017: Weighted F1 = 0.9963

Evaluation on date 2019: Weighted F1 = 0.7152

Evaluation on date 2020: Weighted F1 = 0.6776

=== Phase 7: Training/Fine-tuning on date: 2020 ===

Classification Report after date 2020:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1106
           1       0.99      0.97      0.98      1006

    accuracy                           0.98      2112
   macro avg       0.98      0.98      0.98      2112
weighted avg       0.98      0.98      0.98      2112

Confusion Matrix after date 2020:
[[1092   14]
 [  31  975]]
Weighted F1-score after date 2020: 0.9786836516532982

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.3850

Evaluation on date 2014: Weighted F1 = 0.3991

Evaluation on date 2015: Weighted F1 = 0.3665

Evaluation on date 2016: Weighted F1 = 0.7929

Evaluation on date 2017: Weighted F1 = 0.9960

Evaluation on date 2019: Weighted F1 = 0.6062

Evaluation on date 2020: Weighted F1 = 0.9787

In [9]:
# ---------------
# Results summary
# ---------------

print("\n=== Results Summary ===")
for date, res in results.items():
    print(f"\nResults after training on date {date}:")
    for test_date, f1 in res.items():
        print(f"  Test on date {test_date}: Weighted F1 = {f1:.4f}")

=== Results Summary ===

Results after training on date 2011-2013:
  Test on date 2011-2013: Weighted F1 = 0.3850
  Test on date 2014: Weighted F1 = 0.3095
  Test on date 2015: Weighted F1 = 0.3665
  Test on date 2016: Weighted F1 = 0.2058
  Test on date 2017: Weighted F1 = 0.0000
  Test on date 2019: Weighted F1 = 0.2163
  Test on date 2020: Weighted F1 = 0.3074

Results after training on date 2014:
  Test on date 2011-2013: Weighted F1 = 0.3850
  Test on date 2014: Weighted F1 = 0.3095
  Test on date 2015: Weighted F1 = 0.3665
  Test on date 2016: Weighted F1 = 0.2058
  Test on date 2017: Weighted F1 = 0.0000
  Test on date 2019: Weighted F1 = 0.2163
  Test on date 2020: Weighted F1 = 0.3074

Results after training on date 2015:
  Test on date 2011-2013: Weighted F1 = 0.3850
  Test on date 2014: Weighted F1 = 0.3095
  Test on date 2015: Weighted F1 = 0.3665
  Test on date 2016: Weighted F1 = 0.2058
  Test on date 2017: Weighted F1 = 0.0000
  Test on date 2019: Weighted F1 = 0.2163
  Test on date 2020: Weighted F1 = 0.3074

Results after training on date 2016:
  Test on date 2011-2013: Weighted F1 = 0.4455
  Test on date 2014: Weighted F1 = 0.3944
  Test on date 2015: Weighted F1 = 0.3055
  Test on date 2016: Weighted F1 = 0.9887
  Test on date 2017: Weighted F1 = 0.9952
  Test on date 2019: Weighted F1 = 0.2373
  Test on date 2020: Weighted F1 = 0.4730

Results after training on date 2017:
  Test on date 2011-2013: Weighted F1 = 0.4455
  Test on date 2014: Weighted F1 = 0.4004
  Test on date 2015: Weighted F1 = 0.5092
  Test on date 2016: Weighted F1 = 0.6445
  Test on date 2017: Weighted F1 = 0.9959
  Test on date 2019: Weighted F1 = 0.4612
  Test on date 2020: Weighted F1 = 0.4118

Results after training on date 2019:
  Test on date 2011-2013: Weighted F1 = 0.4935
  Test on date 2014: Weighted F1 = 0.3991
  Test on date 2015: Weighted F1 = 0.3388
  Test on date 2016: Weighted F1 = 0.9482
  Test on date 2017: Weighted F1 = 0.9963
  Test on date 2019: Weighted F1 = 0.7152
  Test on date 2020: Weighted F1 = 0.6776

Results after training on date 2020:
  Test on date 2011-2013: Weighted F1 = 0.3850
  Test on date 2014: Weighted F1 = 0.3991
  Test on date 2015: Weighted F1 = 0.3665
  Test on date 2016: Weighted F1 = 0.7929
  Test on date 2017: Weighted F1 = 0.9960
  Test on date 2019: Weighted F1 = 0.6062
  Test on date 2020: Weighted F1 = 0.9787