# **DeBERTa**

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1" # "0" o "1"

In [2]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cuda

In [3]:
from utils import *

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, classification_report, confusion_matrix
from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
)

/home/n.emmolo/miniconda3/envs/env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-11-08 18:24:36.050305: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-08 18:24:36.109290: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-08 18:24:37.383351: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [4]:
# Ignore warnings for cleaner output
import warnings
warnings.filterwarnings("ignore")

In [5]:
# --------------------
# Build model function
# --------------------

def build_model(learning_rate=2e-5, weight_decay=0.1):
    """
    Builds a RoBERTa model (roberta-base) for sequence classification.

    Args:
        learning_rate (float): Learning rate for the optimizer.
        weight_decay (float): Weight decay for AdamW optimizer.

    Returns:
        model (AutoModelForSequenceClassification): HuggingFace RoBERTa model.
        tokenizer (AutoTokenizer): Tokenizer associated with the model.
        train_args (TrainingArguments): Default training configuration.
    """

    model = AutoModelForSequenceClassification.from_pretrained("roberta-base", num_labels=2)
    tokenizer = AutoTokenizer.from_pretrained("roberta-base")

    train_args = TrainingArguments(
        output_dir="./roberta_finetune_output",
        eval_strategy="epoch",
        save_strategy="no",
        learning_rate=learning_rate,
        weight_decay=weight_decay,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        logging_dir="./logs",
        load_best_model_at_end=False,
        logging_steps=50,
        seed=42,
    )

    return model, tokenizer, train_args

In [6]:
# ----------------------
# Tokenization functions
# ----------------------

def tokenize_function(examples, tokenizer, max_len=128):
    """
    Tokenizes the input examples using the provided tokenizer.

    Args:
        examples (dict): A dictionary containing the text data to be tokenized.
        tokenizer (AutoTokenizer): The tokenizer to use for tokenization.
        max_len (int): Maximum length for padding/truncation.

    Returns:
        dict: Tokenized inputs with padding and truncation applied.
    """

    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=max_len,
    )


def tokenize_datasets(datasets, tokenizer):
    """
    Tokenizes multiple datasets using the provided tokenizer.

    Args:
        datasets (dict): A dictionary where keys are dataset names and values are dictionaries with 'train', 'val', and 'test' splits.
        tokenizer (AutoTokenizer): The tokenizer to use for tokenization.

    Returns:
        dict: A dictionary with the same keys as input datasets, but with tokenized datasets.
    """

    tokenized_datasets = {}
    
    for name, data in datasets.items():
        print(f"\n=== Tokenizing dataset: {name} ===")

        train_dataset = Dataset.from_dict({"text": data["train"][0], "label": data["train"][1].astype(int)})
        val_dataset = Dataset.from_dict({"text": data["val"][0], "label": data["val"][1].astype(int)})
        test_dataset = Dataset.from_dict({"text": data["test"][0], "label": data["test"][1].astype(int)})

        train_tokenized = train_dataset.map(lambda x: tokenize_function(x, tokenizer), batched=True)
        val_tokenized = val_dataset.map(lambda x: tokenize_function(x, tokenizer), batched=True)
        test_tokenized = test_dataset.map(lambda x: tokenize_function(x, tokenizer), batched=True)

        tokenized_datasets[name] = {
            "train": (train_tokenized, np.array(train_dataset["label"])),
            "val": (val_tokenized, np.array(val_dataset["label"])),
            "test": (test_tokenized, np.array(test_dataset["label"]))
        }

    return tokenized_datasets

## VERSION 1: Dataset (Simple)

In [7]:
dataset_df = data_loading() # load all datasets

for name, df in dataset_df.items():
    print(f"Name: {name}, Number of samples: {len(df)}")

# dataset_df = dict(list(dataset_df.items())[:5])

print("\nSplitting datasets into train/val/test...")
datasets = {name: split_dataset(df) for name, df in dataset_df.items()} # split all datasets in train/val/test

model, tokenizer, train_args = build_model()

print("\nComputing tokenized datasets...")
datasets =  tokenize_datasets(datasets, tokenizer) # tokenize all datasets

Name: Celebrity, Number of samples: 500
Name: CIDII, Number of samples: 722
Name: FaKES, Number of samples: 842
Name: FakeVsSatire, Number of samples: 486
Name: Horne, Number of samples: 326
Name: Infodemic, Number of samples: 10559
Name: ISOT, Number of samples: 44271
Name: Kaggle_clement, Number of samples: 39105
Name: Kaggle_meg, Number of samples: 12845
Name: LIAR_PLUS, Number of samples: 12784
Name: Politifact, Number of samples: 504
Name: Unipi_NDF, Number of samples: 554

Splitting datasets into train/val/test...

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Computing tokenized datasets...

=== Tokenizing dataset: Celebrity ===

Map: 100%|███████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 1871.67 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1810.46 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1848.57 examples/s]

=== Tokenizing dataset: CIDII ===

Map: 100%|███████████████████████████████████████████████████████████████| 433/433 [00:00<00:00, 6686.18 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 144/144 [00:00<00:00, 4843.89 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 145/145 [00:00<00:00, 3354.76 examples/s]

=== Tokenizing dataset: FaKES ===

Map: 100%|███████████████████████████████████████████████████████████████| 505/505 [00:00<00:00, 3822.52 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 168/168 [00:00<00:00, 2987.08 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 169/169 [00:00<00:00, 3228.92 examples/s]

=== Tokenizing dataset: FakeVsSatire ===

Map: 100%|███████████████████████████████████████████████████████████████| 291/291 [00:00<00:00, 2161.17 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████| 97/97 [00:00<00:00, 1901.01 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 1761.51 examples/s]

=== Tokenizing dataset: Horne ===

Map: 100%|███████████████████████████████████████████████████████████████| 195/195 [00:00<00:00, 1593.74 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 65/65 [00:00<00:00, 966.42 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 66/66 [00:00<00:00, 976.21 examples/s]

=== Tokenizing dataset: Infodemic ===

Map: 100%|████████████████████████████████████████████████████████████| 6335/6335 [00:00<00:00, 12840.56 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 12989.57 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 12653.68 examples/s]

=== Tokenizing dataset: ISOT ===

Map: 100%|███████████████████████████████████████████████████████████| 26562/26562 [00:08<00:00, 3042.77 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 8854/8854 [00:02<00:00, 3098.00 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 8855/8855 [00:02<00:00, 3263.92 examples/s]

=== Tokenizing dataset: Kaggle_clement ===

Map: 100%|███████████████████████████████████████████████████████████| 23463/23463 [00:07<00:00, 3091.29 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 7821/7821 [00:02<00:00, 3296.05 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 7821/7821 [00:02<00:00, 3305.98 examples/s]

=== Tokenizing dataset: Kaggle_meg ===

Map: 100%|█████████████████████████████████████████████████████████████| 7707/7707 [00:03<00:00, 2026.81 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 2045.10 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 1844.97 examples/s]

=== Tokenizing dataset: LIAR_PLUS ===

Map: 100%|████████████████████████████████████████████████████████████| 7670/7670 [00:00<00:00, 14055.67 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2557/2557 [00:00<00:00, 14108.01 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2557/2557 [00:00<00:00, 14549.47 examples/s]

=== Tokenizing dataset: Politifact ===

Map: 100%|███████████████████████████████████████████████████████████████| 302/302 [00:00<00:00, 1179.63 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 943.63 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 923.90 examples/s]

=== Tokenizing dataset: Unipi_NDF ===

Map: 100%|███████████████████████████████████████████████████████████████| 332/332 [00:00<00:00, 6454.39 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 3974.90 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 4533.85 examples/s]

In [8]:
# --------------------------------
# Fine-tuning on multiple datasets
# --------------------------------

results = {}

for i, (name, data) in enumerate(datasets.items()):
    print(f"\n=== Phase {i+1}: Fine-tuning on {name} ===")

    X_train, y_train = data["train"]
    X_val, y_val = data["val"]
    X_test, y_test = data["test"]

    # define trainer
    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=X_train,
        eval_dataset=X_val,
    )

    # fine-tune on train + val
    trainer.train()

    # evaluate on current dataset
    y_pred = trainer.predict(X_test)
    y_pred = np.argmax(y_pred.predictions, axis=1)
    print(f"\nClassification Report after {name}:")
    print(classification_report(y_test, y_pred))
    print(f"Confusion Matrix after {name}:")
    print(confusion_matrix(y_test, y_pred))
    print(f"Weighted F1-score after {name}: {f1_score(y_test, y_pred, average='weighted'):.4f}")

    # evaluate on all datasets
    print("\n--- Evaluation on all datasets ---")
    results[name] = {}
    for test_name, test_data in datasets.items():
        X_te, y_te = test_data["test"]
        preds = trainer.predict(X_te)
        preds = np.argmax(preds.predictions, axis=1)
        f1 = f1_score(y_te, preds, average="weighted")
        results[name][test_name] = f1
        print(f"Evaluation on {test_name}: Weighted F1 = {f1:.4f}")

=== Phase 1: Fine-tuning on Celebrity ===

Classification Report after Celebrity:
              precision    recall  f1-score   support

           0       0.82      0.80      0.81        50
           1       0.80      0.82      0.81        50

    accuracy                           0.81       100
   macro avg       0.81      0.81      0.81       100
weighted avg       0.81      0.81      0.81       100

Confusion Matrix after Celebrity:
[[40 10]
 [ 9 41]]
Weighted F1-score after Celebrity: 0.8100

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.8100

Evaluation on CIDII: Weighted F1 = 0.5631

Evaluation on FaKES: Weighted F1 = 0.3779

Evaluation on FakeVsSatire: Weighted F1 = 0.6652

Evaluation on Horne: Weighted F1 = 0.5775

Evaluation on Infodemic: Weighted F1 = 0.4063

Evaluation on ISOT: Weighted F1 = 0.4362

Evaluation on Kaggle_clement: Weighted F1 = 0.7341

Evaluation on Kaggle_meg: Weighted F1 = 0.8868

Evaluation on LIAR_PLUS: Weighted F1 = 0.4176

Evaluation on Politifact: Weighted F1 = 0.5997

Evaluation on Unipi_NDF: Weighted F1 = 0.5417

=== Phase 2: Fine-tuning on CIDII ===

Classification Report after CIDII:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98        85
           1       0.98      0.97      0.97        60

    accuracy                           0.98       145
   macro avg       0.98      0.98      0.98       145
weighted avg       0.98      0.98      0.98       145

Confusion Matrix after CIDII:
[[84  1]
 [ 2 58]]
Weighted F1-score after CIDII: 0.9793

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.5072

Evaluation on CIDII: Weighted F1 = 0.9793

Evaluation on FaKES: Weighted F1 = 0.3241

Evaluation on FakeVsSatire: Weighted F1 = 0.4452

Evaluation on Horne: Weighted F1 = 0.4099

Evaluation on Infodemic: Weighted F1 = 0.4067

Evaluation on ISOT: Weighted F1 = 0.8283

Evaluation on Kaggle_clement: Weighted F1 = 0.7792

Evaluation on Kaggle_meg: Weighted F1 = 0.0971

Evaluation on LIAR_PLUS: Weighted F1 = 0.3218

Evaluation on Politifact: Weighted F1 = 0.7091

Evaluation on Unipi_NDF: Weighted F1 = 0.2542

=== Phase 3: Fine-tuning on FaKES ===

Classification Report after FaKES:
              precision    recall  f1-score   support

           0       0.52      0.78      0.62        89
           1       0.46      0.21      0.29        80

    accuracy                           0.51       169
   macro avg       0.49      0.49      0.46       169
weighted avg       0.49      0.51      0.47       169

Confusion Matrix after FaKES:
[[69 20]
 [63 17]]
Weighted F1-score after FaKES: 0.4664

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.7494

Evaluation on CIDII: Weighted F1 = 0.8939

Evaluation on FaKES: Weighted F1 = 0.4664

Evaluation on FakeVsSatire: Weighted F1 = 0.6735

Evaluation on Horne: Weighted F1 = 0.6854

Evaluation on Infodemic: Weighted F1 = 0.7018

Evaluation on ISOT: Weighted F1 = 0.7384

Evaluation on Kaggle_clement: Weighted F1 = 0.9079

Evaluation on Kaggle_meg: Weighted F1 = 0.5643

Evaluation on LIAR_PLUS: Weighted F1 = 0.5729

Evaluation on Politifact: Weighted F1 = 0.7102

Evaluation on Unipi_NDF: Weighted F1 = 0.6028

=== Phase 4: Fine-tuning on FakeVsSatire ===

Classification Report after FakeVsSatire:
              precision    recall  f1-score   support

           0       0.83      0.71      0.76        41
           1       0.81      0.89      0.85        57

    accuracy                           0.82        98
   macro avg       0.82      0.80      0.81        98
weighted avg       0.82      0.82      0.81        98

Confusion Matrix after FakeVsSatire:
[[29 12]
 [ 6 51]]
Weighted F1-score after FakeVsSatire: 0.8137

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.7348

Evaluation on CIDII: Weighted F1 = 0.9377

Evaluation on FaKES: Weighted F1 = 0.5322

Evaluation on FakeVsSatire: Weighted F1 = 0.8137

Evaluation on Horne: Weighted F1 = 0.6382

Evaluation on Infodemic: Weighted F1 = 0.5084

Evaluation on ISOT: Weighted F1 = 0.7696

Evaluation on Kaggle_clement: Weighted F1 = 0.9831

Evaluation on Kaggle_meg: Weighted F1 = 0.4368

Evaluation on LIAR_PLUS: Weighted F1 = 0.4741

Evaluation on Politifact: Weighted F1 = 0.7199

Evaluation on Unipi_NDF: Weighted F1 = 0.5568

=== Phase 5: Fine-tuning on Horne ===

Classification Report after Horne:
              precision    recall  f1-score   support

           0       0.86      0.88      0.87        41
           1       0.79      0.76      0.78        25

    accuracy                           0.83        66
   macro avg       0.82      0.82      0.82        66
weighted avg       0.83      0.83      0.83        66

Confusion Matrix after Horne:
[[36  5]
 [ 6 19]]
Weighted F1-score after Horne: 0.8326

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.6480

Evaluation on CIDII: Weighted F1 = 0.9443

Evaluation on FaKES: Weighted F1 = 0.4737

Evaluation on FakeVsSatire: Weighted F1 = 0.7029

Evaluation on Horne: Weighted F1 = 0.8326

Evaluation on Infodemic: Weighted F1 = 0.4440

Evaluation on ISOT: Weighted F1 = 0.9422

Evaluation on Kaggle_clement: Weighted F1 = 0.9917

Evaluation on Kaggle_meg: Weighted F1 = 0.3805

Evaluation on LIAR_PLUS: Weighted F1 = 0.4615

Evaluation on Politifact: Weighted F1 = 0.8285

Evaluation on Unipi_NDF: Weighted F1 = 0.4344

=== Phase 6: Fine-tuning on Infodemic ===

Classification Report after Infodemic:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      1106
           1       0.99      0.98      0.98      1006

    accuracy                           0.98      2112
   macro avg       0.98      0.98      0.98      2112
weighted avg       0.98      0.98      0.98      2112

Confusion Matrix after Infodemic:
[[1093   13]
 [  25  981]]
Weighted F1-score after Infodemic: 0.9820

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3552

Evaluation on CIDII: Weighted F1 = 0.3400

Evaluation on FaKES: Weighted F1 = 0.3548

Evaluation on FakeVsSatire: Weighted F1 = 0.4278

Evaluation on Horne: Weighted F1 = 0.2081

Evaluation on Infodemic: Weighted F1 = 0.9820

Evaluation on ISOT: Weighted F1 = 0.4464

Evaluation on Kaggle_clement: Weighted F1 = 0.3974

Evaluation on Kaggle_meg: Weighted F1 = 0.0117

Evaluation on LIAR_PLUS: Weighted F1 = 0.2927

Evaluation on Politifact: Weighted F1 = 0.4627

Evaluation on Unipi_NDF: Weighted F1 = 0.4184

=== Phase 7: Fine-tuning on ISOT ===

Classification Report after ISOT:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4284
           1       1.00      1.00      1.00      4571

    accuracy                           1.00      8855
   macro avg       1.00      1.00      1.00      8855
weighted avg       1.00      1.00      1.00      8855

Confusion Matrix after ISOT:
[[4284    0]
 [   1 4570]]
Weighted F1-score after ISOT: 0.9999

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3333

Evaluation on CIDII: Weighted F1 = 0.5459

Evaluation on FaKES: Weighted F1 = 0.3171

Evaluation on FakeVsSatire: Weighted F1 = 0.4203

Evaluation on Horne: Weighted F1 = 0.4759

Evaluation on Infodemic: Weighted F1 = 0.6598

Evaluation on ISOT: Weighted F1 = 0.9999

Evaluation on Kaggle_clement: Weighted F1 = 0.7082

Evaluation on Kaggle_meg: Weighted F1 = 0.0171

Evaluation on LIAR_PLUS: Weighted F1 = 0.2721

Evaluation on Politifact: Weighted F1 = 0.4925

Evaluation on Unipi_NDF: Weighted F1 = 0.3199

=== Phase 8: Fine-tuning on Kaggle_clement ===

Classification Report after Kaggle_clement:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4240
           1       1.00      1.00      1.00      3581

    accuracy                           1.00      7821
   macro avg       1.00      1.00      1.00      7821
weighted avg       1.00      1.00      1.00      7821

Confusion Matrix after Kaggle_clement:
[[4239    1]
 [   0 3581]]
Weighted F1-score after Kaggle_clement: 0.9999

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3967

Evaluation on CIDII: Weighted F1 = 0.5781

Evaluation on FaKES: Weighted F1 = 0.5098

Evaluation on FakeVsSatire: Weighted F1 = 0.4723

Evaluation on Horne: Weighted F1 = 0.5892

Evaluation on Infodemic: Weighted F1 = 0.5353

Evaluation on ISOT: Weighted F1 = 0.9909

Evaluation on Kaggle_clement: Weighted F1 = 0.9999

Evaluation on Kaggle_meg: Weighted F1 = 0.1270

Evaluation on LIAR_PLUS: Weighted F1 = 0.5002

Evaluation on Politifact: Weighted F1 = 0.4471

Evaluation on Unipi_NDF: Weighted F1 = 0.4280

=== Phase 9: Fine-tuning on Kaggle_meg ===

Classification Report after Kaggle_meg:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2514
           1       0.62      0.09      0.16        55

    accuracy                           0.98      2569
   macro avg       0.80      0.54      0.57      2569
weighted avg       0.97      0.98      0.97      2569

Confusion Matrix after Kaggle_meg:
[[2511    3]
 [  50    5]]
Weighted F1-score after Kaggle_meg: 0.9718

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3333

Evaluation on CIDII: Weighted F1 = 0.4333

Evaluation on FaKES: Weighted F1 = 0.3633

Evaluation on FakeVsSatire: Weighted F1 = 0.2468

Evaluation on Horne: Weighted F1 = 0.4761

Evaluation on Infodemic: Weighted F1 = 0.3600

Evaluation on ISOT: Weighted F1 = 0.3056

Evaluation on Kaggle_clement: Weighted F1 = 0.3790

Evaluation on Kaggle_meg: Weighted F1 = 0.9718

Evaluation on LIAR_PLUS: Weighted F1 = 0.3993

Evaluation on Politifact: Weighted F1 = 0.5040

Evaluation on Unipi_NDF: Weighted F1 = 0.4654

=== Phase 10: Fine-tuning on LIAR_PLUS ===

Classification Report after LIAR_PLUS:
              precision    recall  f1-score   support

           0       0.65      0.76      0.70      1426
           1       0.61      0.48      0.53      1131

    accuracy                           0.63      2557
   macro avg       0.63      0.62      0.62      2557
weighted avg       0.63      0.63      0.63      2557

Confusion Matrix after LIAR_PLUS:
[[1078  348]
 [ 591  540]]
Weighted F1-score after LIAR_PLUS: 0.6251

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3763

Evaluation on CIDII: Weighted F1 = 0.4050

Evaluation on FaKES: Weighted F1 = 0.4494

Evaluation on FakeVsSatire: Weighted F1 = 0.4609

Evaluation on Horne: Weighted F1 = 0.3965

Evaluation on Infodemic: Weighted F1 = 0.7316

Evaluation on ISOT: Weighted F1 = 0.2990

Evaluation on Kaggle_clement: Weighted F1 = 0.2921

Evaluation on Kaggle_meg: Weighted F1 = 0.4029

Evaluation on LIAR_PLUS: Weighted F1 = 0.6251

Evaluation on Politifact: Weighted F1 = 0.5496

Evaluation on Unipi_NDF: Weighted F1 = 0.4024

=== Phase 11: Fine-tuning on Politifact ===

Classification Report after Politifact:
              precision    recall  f1-score   support

           0       0.96      0.82      0.88        65
           1       0.74      0.94      0.83        36

    accuracy                           0.86       101
   macro avg       0.85      0.88      0.86       101
weighted avg       0.88      0.86      0.86       101

Confusion Matrix after Politifact:
[[53 12]
 [ 2 34]]
Weighted F1-score after Politifact: 0.8641

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.3711

Evaluation on CIDII: Weighted F1 = 0.3772

Evaluation on FaKES: Weighted F1 = 0.5078

Evaluation on FakeVsSatire: Weighted F1 = 0.5891

Evaluation on Horne: Weighted F1 = 0.5056

Evaluation on Infodemic: Weighted F1 = 0.8011

Evaluation on ISOT: Weighted F1 = 0.7727

Evaluation on Kaggle_clement: Weighted F1 = 0.8497

Evaluation on Kaggle_meg: Weighted F1 = 0.4890

Evaluation on LIAR_PLUS: Weighted F1 = 0.5930

Evaluation on Politifact: Weighted F1 = 0.8641

Evaluation on Unipi_NDF: Weighted F1 = 0.2855

=== Phase 12: Fine-tuning on Unipi_NDF ===

Classification Report after Unipi_NDF:
              precision    recall  f1-score   support

           0       0.90      0.97      0.94        68
           1       0.95      0.84      0.89        43

    accuracy                           0.92       111
   macro avg       0.93      0.90      0.91       111
weighted avg       0.92      0.92      0.92       111

Confusion Matrix after Unipi_NDF:
[[66  2]
 [ 7 36]]
Weighted F1-score after Unipi_NDF: 0.9179

--- Evaluation on all datasets ---

Evaluation on Celebrity: Weighted F1 = 0.6339

Evaluation on CIDII: Weighted F1 = 0.3489

Evaluation on FaKES: Weighted F1 = 0.4440

Evaluation on FakeVsSatire: Weighted F1 = 0.6129

Evaluation on Horne: Weighted F1 = 0.4920

Evaluation on Infodemic: Weighted F1 = 0.8173

Evaluation on ISOT: Weighted F1 = 0.7507

Evaluation on Kaggle_clement: Weighted F1 = 0.8059

Evaluation on Kaggle_meg: Weighted F1 = 0.4791

Evaluation on LIAR_PLUS: Weighted F1 = 0.5937

Evaluation on Politifact: Weighted F1 = 0.8228

Evaluation on Unipi_NDF: Weighted F1 = 0.9179

In [9]:
# ---------------
# Results summary
# ---------------

print("\n=== Results Summary ===")
for name, res in results.items():
    print(f"\nResults after training on {name}:")
    for test_name, f1 in res.items():
        print(f"  Test on {test_name}: Weighted F1 = {f1:.4f}")

=== Results Summary ===

Results after training on Celebrity:
  Test on Celebrity: Weighted F1 = 0.8100
  Test on CIDII: Weighted F1 = 0.5631
  Test on FaKES: Weighted F1 = 0.3779
  Test on FakeVsSatire: Weighted F1 = 0.6652
  Test on Horne: Weighted F1 = 0.5775
  Test on Infodemic: Weighted F1 = 0.4063
  Test on ISOT: Weighted F1 = 0.4362
  Test on Kaggle_clement: Weighted F1 = 0.7341
  Test on Kaggle_meg: Weighted F1 = 0.8868
  Test on LIAR_PLUS: Weighted F1 = 0.4176
  Test on Politifact: Weighted F1 = 0.5997
  Test on Unipi_NDF: Weighted F1 = 0.5417

Results after training on CIDII:
  Test on Celebrity: Weighted F1 = 0.5072
  Test on CIDII: Weighted F1 = 0.9793
  Test on FaKES: Weighted F1 = 0.3241
  Test on FakeVsSatire: Weighted F1 = 0.4452
  Test on Horne: Weighted F1 = 0.4099
  Test on Infodemic: Weighted F1 = 0.4067
  Test on ISOT: Weighted F1 = 0.8283
  Test on Kaggle_clement: Weighted F1 = 0.7792
  Test on Kaggle_meg: Weighted F1 = 0.0971
  Test on LIAR_PLUS: Weighted F1 = 0.3218
  Test on Politifact: Weighted F1 = 0.7091
  Test on Unipi_NDF: Weighted F1 = 0.2542

Results after training on FaKES:
  Test on Celebrity: Weighted F1 = 0.7494
  Test on CIDII: Weighted F1 = 0.8939
  Test on FaKES: Weighted F1 = 0.4664
  Test on FakeVsSatire: Weighted F1 = 0.6735
  Test on Horne: Weighted F1 = 0.6854
  Test on Infodemic: Weighted F1 = 0.7018
  Test on ISOT: Weighted F1 = 0.7384
  Test on Kaggle_clement: Weighted F1 = 0.9079
  Test on Kaggle_meg: Weighted F1 = 0.5643
  Test on LIAR_PLUS: Weighted F1 = 0.5729
  Test on Politifact: Weighted F1 = 0.7102
  Test on Unipi_NDF: Weighted F1 = 0.6028

Results after training on FakeVsSatire:
  Test on Celebrity: Weighted F1 = 0.7348
  Test on CIDII: Weighted F1 = 0.9377
  Test on FaKES: Weighted F1 = 0.5322
  Test on FakeVsSatire: Weighted F1 = 0.8137
  Test on Horne: Weighted F1 = 0.6382
  Test on Infodemic: Weighted F1 = 0.5084
  Test on ISOT: Weighted F1 = 0.7696
  Test on Kaggle_clement: Weighted F1 = 0.9831
  Test on Kaggle_meg: Weighted F1 = 0.4368
  Test on LIAR_PLUS: Weighted F1 = 0.4741
  Test on Politifact: Weighted F1 = 0.7199
  Test on Unipi_NDF: Weighted F1 = 0.5568

Results after training on Horne:
  Test on Celebrity: Weighted F1 = 0.6480
  Test on CIDII: Weighted F1 = 0.9443
  Test on FaKES: Weighted F1 = 0.4737
  Test on FakeVsSatire: Weighted F1 = 0.7029
  Test on Horne: Weighted F1 = 0.8326
  Test on Infodemic: Weighted F1 = 0.4440
  Test on ISOT: Weighted F1 = 0.9422
  Test on Kaggle_clement: Weighted F1 = 0.9917
  Test on Kaggle_meg: Weighted F1 = 0.3805
  Test on LIAR_PLUS: Weighted F1 = 0.4615
  Test on Politifact: Weighted F1 = 0.8285
  Test on Unipi_NDF: Weighted F1 = 0.4344

Results after training on Infodemic:
  Test on Celebrity: Weighted F1 = 0.3552
  Test on CIDII: Weighted F1 = 0.3400
  Test on FaKES: Weighted F1 = 0.3548
  Test on FakeVsSatire: Weighted F1 = 0.4278
  Test on Horne: Weighted F1 = 0.2081
  Test on Infodemic: Weighted F1 = 0.9820
  Test on ISOT: Weighted F1 = 0.4464
  Test on Kaggle_clement: Weighted F1 = 0.3974
  Test on Kaggle_meg: Weighted F1 = 0.0117
  Test on LIAR_PLUS: Weighted F1 = 0.2927
  Test on Politifact: Weighted F1 = 0.4627
  Test on Unipi_NDF: Weighted F1 = 0.4184

Results after training on ISOT:
  Test on Celebrity: Weighted F1 = 0.3333
  Test on CIDII: Weighted F1 = 0.5459
  Test on FaKES: Weighted F1 = 0.3171
  Test on FakeVsSatire: Weighted F1 = 0.4203
  Test on Horne: Weighted F1 = 0.4759
  Test on Infodemic: Weighted F1 = 0.6598
  Test on ISOT: Weighted F1 = 0.9999
  Test on Kaggle_clement: Weighted F1 = 0.7082
  Test on Kaggle_meg: Weighted F1 = 0.0171
  Test on LIAR_PLUS: Weighted F1 = 0.2721
  Test on Politifact: Weighted F1 = 0.4925
  Test on Unipi_NDF: Weighted F1 = 0.3199

Results after training on Kaggle_clement:
  Test on Celebrity: Weighted F1 = 0.3967
  Test on CIDII: Weighted F1 = 0.5781
  Test on FaKES: Weighted F1 = 0.5098
  Test on FakeVsSatire: Weighted F1 = 0.4723
  Test on Horne: Weighted F1 = 0.5892
  Test on Infodemic: Weighted F1 = 0.5353
  Test on ISOT: Weighted F1 = 0.9909
  Test on Kaggle_clement: Weighted F1 = 0.9999
  Test on Kaggle_meg: Weighted F1 = 0.1270
  Test on LIAR_PLUS: Weighted F1 = 0.5002
  Test on Politifact: Weighted F1 = 0.4471
  Test on Unipi_NDF: Weighted F1 = 0.4280

Results after training on Kaggle_meg:
  Test on Celebrity: Weighted F1 = 0.3333
  Test on CIDII: Weighted F1 = 0.4333
  Test on FaKES: Weighted F1 = 0.3633
  Test on FakeVsSatire: Weighted F1 = 0.2468
  Test on Horne: Weighted F1 = 0.4761
  Test on Infodemic: Weighted F1 = 0.3600
  Test on ISOT: Weighted F1 = 0.3056
  Test on Kaggle_clement: Weighted F1 = 0.3790
  Test on Kaggle_meg: Weighted F1 = 0.9718
  Test on LIAR_PLUS: Weighted F1 = 0.3993
  Test on Politifact: Weighted F1 = 0.5040
  Test on Unipi_NDF: Weighted F1 = 0.4654

Results after training on LIAR_PLUS:
  Test on Celebrity: Weighted F1 = 0.3763
  Test on CIDII: Weighted F1 = 0.4050
  Test on FaKES: Weighted F1 = 0.4494
  Test on FakeVsSatire: Weighted F1 = 0.4609
  Test on Horne: Weighted F1 = 0.3965
  Test on Infodemic: Weighted F1 = 0.7316
  Test on ISOT: Weighted F1 = 0.2990
  Test on Kaggle_clement: Weighted F1 = 0.2921
  Test on Kaggle_meg: Weighted F1 = 0.4029
  Test on LIAR_PLUS: Weighted F1 = 0.6251
  Test on Politifact: Weighted F1 = 0.5496
  Test on Unipi_NDF: Weighted F1 = 0.4024

Results after training on Politifact:
  Test on Celebrity: Weighted F1 = 0.3711
  Test on CIDII: Weighted F1 = 0.3772
  Test on FaKES: Weighted F1 = 0.5078
  Test on FakeVsSatire: Weighted F1 = 0.5891
  Test on Horne: Weighted F1 = 0.5056
  Test on Infodemic: Weighted F1 = 0.8011
  Test on ISOT: Weighted F1 = 0.7727
  Test on Kaggle_clement: Weighted F1 = 0.8497
  Test on Kaggle_meg: Weighted F1 = 0.4890
  Test on LIAR_PLUS: Weighted F1 = 0.5930
  Test on Politifact: Weighted F1 = 0.8641
  Test on Unipi_NDF: Weighted F1 = 0.2855

Results after training on Unipi_NDF:
  Test on Celebrity: Weighted F1 = 0.6339
  Test on CIDII: Weighted F1 = 0.3489
  Test on FaKES: Weighted F1 = 0.4440
  Test on FakeVsSatire: Weighted F1 = 0.6129
  Test on Horne: Weighted F1 = 0.4920
  Test on Infodemic: Weighted F1 = 0.8173
  Test on ISOT: Weighted F1 = 0.7507
  Test on Kaggle_clement: Weighted F1 = 0.8059
  Test on Kaggle_meg: Weighted F1 = 0.4791
  Test on LIAR_PLUS: Weighted F1 = 0.5937
  Test on Politifact: Weighted F1 = 0.8228
  Test on Unipi_NDF: Weighted F1 = 0.9179

## VERSION 2: Dataset by Topic

In [7]:
dataset_df = data_by_topic()

# split "politics" in "politics1" and "politics2"
if "politics" in dataset_df:
    dataset_df["politics1"] = dataset_df["politics"].sample(frac=0.5, random_state=42)
    dataset_df["politics2"] = dataset_df["politics"].drop(dataset_df["politics1"].index)
    # drop original "politics" dataset
    del dataset_df["politics"]
    # put "politics1" and "politics2" at the beginning of the dict
    dataset_df = {"politics1": dataset_df["politics1"], "politics2": dataset_df["politics2"], **dataset_df}

for topic, df in dataset_df.items():
    print(f"Topic: {topic}, Number of samples: {len(df)}")

# dataset_df = dict(list(dataset_df.items())[3:]) # remove first 3 datasets

print("\nSplitting datasets into train/val/test...")
datasets = {topic: split_dataset(df) for topic, df in dataset_df.items()} # split all datasets in train/val/test

model, tokenizer, train_args = build_model()

print("\nComputing tokenized datasets...")
datasets =  tokenize_datasets(datasets, tokenizer) # tokenize all datasets

Topic: politics1, Number of samples: 48738
Topic: politics2, Number of samples: 48738
Topic: general, Number of samples: 12845
Topic: covid, Number of samples: 10559
Topic: syria, Number of samples: 842
Topic: islam, Number of samples: 722
Topic: notredame, Number of samples: 554
Topic: gossip, Number of samples: 500

Splitting datasets into train/val/test...

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Computing tokenized datasets...

=== Tokenizing dataset: politics1 ===

Map: 100%|███████████████████████████████████████████████████████████| 29242/29242 [00:08<00:00, 3307.26 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:02<00:00, 3483.75 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:02<00:00, 3541.25 examples/s]

=== Tokenizing dataset: politics2 ===

Map: 100%|███████████████████████████████████████████████████████████| 29242/29242 [00:08<00:00, 3394.61 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:02<00:00, 3421.65 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:02<00:00, 3549.86 examples/s]

=== Tokenizing dataset: general ===

Map: 100%|█████████████████████████████████████████████████████████████| 7707/7707 [00:03<00:00, 2026.29 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 2007.13 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 1845.37 examples/s]

=== Tokenizing dataset: covid ===

Map: 100%|████████████████████████████████████████████████████████████| 6335/6335 [00:00<00:00, 12177.54 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 12481.75 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 11920.19 examples/s]

=== Tokenizing dataset: syria ===

Map: 100%|███████████████████████████████████████████████████████████████| 505/505 [00:00<00:00, 3882.48 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 168/168 [00:00<00:00, 2985.32 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 169/169 [00:00<00:00, 3161.04 examples/s]

=== Tokenizing dataset: islam ===

Map: 100%|███████████████████████████████████████████████████████████████| 433/433 [00:00<00:00, 7133.73 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 144/144 [00:00<00:00, 4658.58 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 145/145 [00:00<00:00, 4011.76 examples/s]

=== Tokenizing dataset: notredame ===

Map: 100%|███████████████████████████████████████████████████████████████| 332/332 [00:00<00:00, 5600.64 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 3924.80 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 3877.89 examples/s]

=== Tokenizing dataset: gossip ===

Map: 100%|███████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 1955.51 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1846.75 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 2193.77 examples/s]

In [8]:
# -------------------------------
# Fine-tuning on Dataset by Topic
# -------------------------------

results = {}

# sequential training
for i, (topic, data) in enumerate(datasets.items()):
    print(f"\n=== Phase {i+1}: Training/Fine-tuning on topic: {topic} ===")

    X_train, y_train = data["train"]
    X_val, y_val = data["val"]
    X_test, y_test = data["test"]

    # define trainer
    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=X_train,
        eval_dataset=X_val,
    )

    # fine-tune on train + val
    trainer.train()

    # evaluate on current dataset
    y_pred = trainer.predict(X_test)
    y_pred = np.argmax(y_pred.predictions, axis=1)
    print(f"\nClassification Report after topic {topic}:")
    print(classification_report(y_test, y_pred))
    print(f"Confusion Matrix after topic {topic}:")
    print(confusion_matrix(y_test, y_pred))
    print(f"Weighted F1-score after topic {topic}:", f1_score(y_test, y_pred, average='weighted'))

    # evaluate on all datasets
    print("\n--- Evaluation on all datasets ---")
    results[topic] = {}
    for test_topic, test_data in datasets.items(): # for each topic
        X_te, y_te = test_data["test"]
        preds = trainer.predict(X_te)
        preds = np.argmax(preds.predictions, axis=1)
        f1 = f1_score(y_te, preds, average="weighted")
        results[topic][test_topic] = f1
        print(f"Evaluation on topic {test_topic}: Weighted F1 = {f1:.4f}")

=== Phase 1: Training/Fine-tuning on topic: politics1 ===

Classification Report after topic politics1:
              precision    recall  f1-score   support

           0       0.94      0.95      0.95      5031
           1       0.95      0.93      0.94      4717

    accuracy                           0.94      9748
   macro avg       0.94      0.94      0.94      9748
weighted avg       0.94      0.94      0.94      9748

Confusion Matrix after topic politics1:
[[4799  232]
 [ 313 4404]]
Weighted F1-score after topic politics1: 0.9440722397757778

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.9441

Evaluation on topic politics2: Weighted F1 = 0.9416

Evaluation on topic general: Weighted F1 = 0.1588

Evaluation on topic covid: Weighted F1 = 0.4562

Evaluation on topic syria: Weighted F1 = 0.4195

Evaluation on topic islam: Weighted F1 = 0.2988

Evaluation on topic notredame: Weighted F1 = 0.3594

Evaluation on topic gossip: Weighted F1 = 0.3404

=== Phase 2: Training/Fine-tuning on topic: politics2 ===

Classification Report after topic politics2:
              precision    recall  f1-score   support

           0       0.93      0.96      0.95      5064
           1       0.95      0.93      0.94      4684

    accuracy                           0.94      9748
   macro avg       0.94      0.94      0.94      9748
weighted avg       0.94      0.94      0.94      9748

Confusion Matrix after topic politics2:
[[4854  210]
 [ 339 4345]]
Weighted F1-score after topic politics2: 0.9436417321758267

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.9463

Evaluation on topic politics2: Weighted F1 = 0.9436

Evaluation on topic general: Weighted F1 = 0.2479

Evaluation on topic covid: Weighted F1 = 0.6153

Evaluation on topic syria: Weighted F1 = 0.5269

Evaluation on topic islam: Weighted F1 = 0.3914

Evaluation on topic notredame: Weighted F1 = 0.4410

Evaluation on topic gossip: Weighted F1 = 0.5249

=== Phase 3: Training/Fine-tuning on topic: general ===

Classification Report after topic general:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2514
           1       0.00      0.00      0.00        55

    accuracy                           0.98      2569
   macro avg       0.49      0.50      0.49      2569
weighted avg       0.96      0.98      0.97      2569

Confusion Matrix after topic general:
[[2514    0]
 [  55    0]]
Weighted F1-score after topic general: 0.9680021644592334

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.3521

Evaluation on topic politics2: Weighted F1 = 0.3564

Evaluation on topic general: Weighted F1 = 0.9680

Evaluation on topic covid: Weighted F1 = 0.3600

Evaluation on topic syria: Weighted F1 = 0.3633

Evaluation on topic islam: Weighted F1 = 0.4333

Evaluation on topic notredame: Weighted F1 = 0.4654

Evaluation on topic gossip: Weighted F1 = 0.3333

=== Phase 4: Training/Fine-tuning on topic: covid ===

Classification Report after topic covid:
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1106
           1       0.98      0.96      0.97      1006

    accuracy                           0.97      2112
   macro avg       0.97      0.97      0.97      2112
weighted avg       0.97      0.97      0.97      2112

Confusion Matrix after topic covid:
[[1086   20]
 [  38  968]]
Weighted F1-score after topic covid: 0.9725247610612786

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.3079

Evaluation on topic politics2: Weighted F1 = 0.3007

Evaluation on topic general: Weighted F1 = 0.0040

Evaluation on topic covid: Weighted F1 = 0.9725

Evaluation on topic syria: Weighted F1 = 0.3042

Evaluation on topic islam: Weighted F1 = 0.2422

Evaluation on topic notredame: Weighted F1 = 0.3463

Evaluation on topic gossip: Weighted F1 = 0.3333

=== Phase 5: Training/Fine-tuning on topic: syria ===

Classification Report after topic syria:
              precision    recall  f1-score   support

           0       0.53      0.30      0.39        89
           1       0.47      0.70      0.57        80

    accuracy                           0.49       169
   macro avg       0.50      0.50      0.48       169
weighted avg       0.50      0.49      0.47       169

Confusion Matrix after topic syria:
[[27 62]
 [24 56]]
Weighted F1-score after topic syria: 0.47089406320175553

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.4031

Evaluation on topic politics2: Weighted F1 = 0.3914

Evaluation on topic general: Weighted F1 = 0.0598

Evaluation on topic covid: Weighted F1 = 0.9414

Evaluation on topic syria: Weighted F1 = 0.4709

Evaluation on topic islam: Weighted F1 = 0.2570

Evaluation on topic notredame: Weighted F1 = 0.5675

Evaluation on topic gossip: Weighted F1 = 0.3503

=== Phase 6: Training/Fine-tuning on topic: islam ===

Classification Report after topic islam:
              precision    recall  f1-score   support

           0       0.95      0.89      0.92        85
           1       0.86      0.93      0.90        60

    accuracy                           0.91       145
   macro avg       0.91      0.91      0.91       145
weighted avg       0.91      0.91      0.91       145

Confusion Matrix after topic islam:
[[76  9]
 [ 4 56]]
Weighted F1-score after topic islam: 0.9107795193312435

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.6073

Evaluation on topic politics2: Weighted F1 = 0.6051

Evaluation on topic general: Weighted F1 = 0.2406

Evaluation on topic covid: Weighted F1 = 0.8520

Evaluation on topic syria: Weighted F1 = 0.5440

Evaluation on topic islam: Weighted F1 = 0.9108

Evaluation on topic notredame: Weighted F1 = 0.7393

Evaluation on topic gossip: Weighted F1 = 0.5175

=== Phase 7: Training/Fine-tuning on topic: notredame ===

Classification Report after topic notredame:
              precision    recall  f1-score   support

           0       0.85      0.88      0.86        68
           1       0.80      0.74      0.77        43

    accuracy                           0.83       111
   macro avg       0.82      0.81      0.82       111
weighted avg       0.83      0.83      0.83       111

Confusion Matrix after topic notredame:
[[60  8]
 [11 32]]
Weighted F1-score after topic notredame: 0.827582544840064

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.5549

Evaluation on topic politics2: Weighted F1 = 0.5405

Evaluation on topic general: Weighted F1 = 0.1612

Evaluation on topic covid: Weighted F1 = 0.9241

Evaluation on topic syria: Weighted F1 = 0.4432

Evaluation on topic islam: Weighted F1 = 0.8280

Evaluation on topic notredame: Weighted F1 = 0.8276

Evaluation on topic gossip: Weighted F1 = 0.4929

=== Phase 8: Training/Fine-tuning on topic: gossip ===

Classification Report after topic gossip:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67        50
           1       0.00      0.00      0.00        50

    accuracy                           0.50       100
   macro avg       0.25      0.50      0.33       100
weighted avg       0.25      0.50      0.33       100

Confusion Matrix after topic gossip:
[[50  0]
 [50  0]]
Weighted F1-score after topic gossip: 0.33333333333333326

--- Evaluation on all datasets ---

Evaluation on topic politics1: Weighted F1 = 0.5406

Evaluation on topic politics2: Weighted F1 = 0.5371

Evaluation on topic general: Weighted F1 = 0.9555

Evaluation on topic covid: Weighted F1 = 0.4430

Evaluation on topic syria: Weighted F1 = 0.3633

Evaluation on topic islam: Weighted F1 = 0.5712

Evaluation on topic notredame: Weighted F1 = 0.4654

Evaluation on topic gossip: Weighted F1 = 0.3333

In [9]:
# ---------------
# Results summary
# ---------------

print("\n=== Results Summary ===")
for topic, res in results.items():
    print(f"\nResults after training on topic {topic}:")
    for test_topic, f1 in res.items():
        print(f"  Test on topic {test_topic}: Weighted F1 = {f1:.4f}")

=== Results Summary ===

Results after training on topic politics1:
  Test on topic politics1: Weighted F1 = 0.9441
  Test on topic politics2: Weighted F1 = 0.9416
  Test on topic general: Weighted F1 = 0.1588
  Test on topic covid: Weighted F1 = 0.4562
  Test on topic syria: Weighted F1 = 0.4195
  Test on topic islam: Weighted F1 = 0.2988
  Test on topic notredame: Weighted F1 = 0.3594
  Test on topic gossip: Weighted F1 = 0.3404

Results after training on topic politics2:
  Test on topic politics1: Weighted F1 = 0.9463
  Test on topic politics2: Weighted F1 = 0.9436
  Test on topic general: Weighted F1 = 0.2479
  Test on topic covid: Weighted F1 = 0.6153
  Test on topic syria: Weighted F1 = 0.5269
  Test on topic islam: Weighted F1 = 0.3914
  Test on topic notredame: Weighted F1 = 0.4410
  Test on topic gossip: Weighted F1 = 0.5249

Results after training on topic general:
  Test on topic politics1: Weighted F1 = 0.3521
  Test on topic politics2: Weighted F1 = 0.3564
  Test on topic general: Weighted F1 = 0.9680
  Test on topic covid: Weighted F1 = 0.3600
  Test on topic syria: Weighted F1 = 0.3633
  Test on topic islam: Weighted F1 = 0.4333
  Test on topic notredame: Weighted F1 = 0.4654
  Test on topic gossip: Weighted F1 = 0.3333

Results after training on topic covid:
  Test on topic politics1: Weighted F1 = 0.3079
  Test on topic politics2: Weighted F1 = 0.3007
  Test on topic general: Weighted F1 = 0.0040
  Test on topic covid: Weighted F1 = 0.9725
  Test on topic syria: Weighted F1 = 0.3042
  Test on topic islam: Weighted F1 = 0.2422
  Test on topic notredame: Weighted F1 = 0.3463
  Test on topic gossip: Weighted F1 = 0.3333

Results after training on topic syria:
  Test on topic politics1: Weighted F1 = 0.4031
  Test on topic politics2: Weighted F1 = 0.3914
  Test on topic general: Weighted F1 = 0.0598
  Test on topic covid: Weighted F1 = 0.9414
  Test on topic syria: Weighted F1 = 0.4709
  Test on topic islam: Weighted F1 = 0.2570
  Test on topic notredame: Weighted F1 = 0.5675
  Test on topic gossip: Weighted F1 = 0.3503

Results after training on topic islam:
  Test on topic politics1: Weighted F1 = 0.6073
  Test on topic politics2: Weighted F1 = 0.6051
  Test on topic general: Weighted F1 = 0.2406
  Test on topic covid: Weighted F1 = 0.8520
  Test on topic syria: Weighted F1 = 0.5440
  Test on topic islam: Weighted F1 = 0.9108
  Test on topic notredame: Weighted F1 = 0.7393
  Test on topic gossip: Weighted F1 = 0.5175

Results after training on topic notredame:
  Test on topic politics1: Weighted F1 = 0.5549
  Test on topic politics2: Weighted F1 = 0.5405
  Test on topic general: Weighted F1 = 0.1612
  Test on topic covid: Weighted F1 = 0.9241
  Test on topic syria: Weighted F1 = 0.4432
  Test on topic islam: Weighted F1 = 0.8280
  Test on topic notredame: Weighted F1 = 0.8276
  Test on topic gossip: Weighted F1 = 0.4929

Results after training on topic gossip:
  Test on topic politics1: Weighted F1 = 0.5406
  Test on topic politics2: Weighted F1 = 0.5371
  Test on topic general: Weighted F1 = 0.9555
  Test on topic covid: Weighted F1 = 0.4430
  Test on topic syria: Weighted F1 = 0.3633
  Test on topic islam: Weighted F1 = 0.5712
  Test on topic notredame: Weighted F1 = 0.4654
  Test on topic gossip: Weighted F1 = 0.3333

## VERSION 3: Dataset by Date

In [7]:
dataset_df = data_by_date()

for date, df in dataset_df.items():
    print(f"Date: {date}, Number of samples: {len(df)}")

# dataset_df = dict(list(dataset_df.items())[:3]) # remove last 3 datasets

print("\nSplitting datasets into train/val/test...")
datasets = {date: split_dataset(df) for date, df in dataset_df.items()} # split all datasets in train/val/test

model, tokenizer, train_args = build_model()

print("\nComputing tokenized datasets...")
datasets =  tokenize_datasets(datasets, tokenizer) # tokenize all datasets

Date: 2011-2013, Number of samples: 55
Date: 2014, Number of samples: 114
Date: 2015, Number of samples: 84
Date: 2016, Number of samples: 63018
Date: 2017, Number of samples: 16657
Date: 2019, Number of samples: 554
Date: 2020, Number of samples: 10559

Splitting datasets into train/val/test...

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Computing tokenized datasets...

=== Tokenizing dataset: 2011-2013 ===

Map: 100%|██████████████████████████████████████████████████████████████████| 33/33 [00:00<00:00, 926.35 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 602.76 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 700.32 examples/s]

=== Tokenizing dataset: 2014 ===

Map: 100%|█████████████████████████████████████████████████████████████████| 68/68 [00:00<00:00, 1861.46 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 985.32 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 1080.30 examples/s]

=== Tokenizing dataset: 2015 ===

Map: 100%|█████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 1430.21 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 1104.14 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 988.10 examples/s]

=== Tokenizing dataset: 2016 ===

Map: 100%|███████████████████████████████████████████████████████████| 37810/37810 [00:15<00:00, 2505.32 examples/s]
Map: 100%|███████████████████████████████████████████████████████████| 12604/12604 [00:04<00:00, 2527.60 examples/s]
Map: 100%|███████████████████████████████████████████████████████████| 12604/12604 [00:04<00:00, 2662.48 examples/s]

=== Tokenizing dataset: 2017 ===

Map: 100%|█████████████████████████████████████████████████████████████| 9994/9994 [00:03<00:00, 3050.76 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 3331/3331 [00:01<00:00, 3305.79 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████| 3332/3332 [00:01<00:00, 3291.79 examples/s]

=== Tokenizing dataset: 2019 ===

Map: 100%|███████████████████████████████████████████████████████████████| 332/332 [00:00<00:00, 5859.69 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 5157.50 examples/s]
Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 3031.77 examples/s]

=== Tokenizing dataset: 2020 ===

Map: 100%|████████████████████████████████████████████████████████████| 6335/6335 [00:00<00:00, 12141.80 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 11907.13 examples/s]
Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 11919.13 examples/s]

In [8]:
# ------------------------------
# Fine-tuning on Dataset by Date
# ------------------------------

results = {}

# sequential training
for i, (date, data) in enumerate(datasets.items()):
    print(f"\n=== Phase {i+1}: Training/Fine-tuning on date: {date} ===")
    
    X_train, y_train = data["train"]
    X_val, y_val = data["val"]
    X_test, y_test = data["test"]

    # define trainer
    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=X_train,
        eval_dataset=X_val,
    )
    
    # fine-tune on train + val
    trainer.train()

    # evaluate on current dataset
    y_pred = trainer.predict(X_test)
    y_pred = np.argmax(y_pred.predictions, axis=1)
    print(f"\nClassification Report after date {date}:")
    print(classification_report(y_test, y_pred))
    print(f"Confusion Matrix after date {date}:")
    print(confusion_matrix(y_test, y_pred))
    print(f"Weighted F1-score after date {date}:", f1_score(y_test, y_pred, average='weighted'))

    # evaluate on all datasets
    print("\n--- Evaluation on all datasets ---")
    results[date] = {}
    for test_date, test_data in datasets.items(): # for each date
        X_te, y_te = test_data["test"]
        preds = trainer.predict(X_te)
        preds = np.argmax(preds.predictions, axis=1)
        f1 = f1_score(y_te, preds, average="weighted")
        results[date][test_date] = f1
        print(f"Evaluation on date {test_date}: Weighted F1 = {f1:.4f}")

=== Phase 1: Training/Fine-tuning on date: 2011-2013 ===

Classification Report after date 2011-2013:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.55      1.00      0.71         6

    accuracy                           0.55        11
   macro avg       0.27      0.50      0.35        11
weighted avg       0.30      0.55      0.39        11

Confusion Matrix after date 2011-2013:
[[0 5]
 [0 6]]
Weighted F1-score after date 2011-2013: 0.3850267379679144

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.3850

Evaluation on date 2014: Weighted F1 = 0.3095

Evaluation on date 2015: Weighted F1 = 0.3665

Evaluation on date 2016: Weighted F1 = 0.2058

Evaluation on date 2017: Weighted F1 = 0.0000

Evaluation on date 2019: Weighted F1 = 0.2163

Evaluation on date 2020: Weighted F1 = 0.3074

=== Phase 2: Training/Fine-tuning on date: 2014 ===

Classification Report after date 2014:
              precision    recall  f1-score   support

           0       0.52      1.00      0.69        12
           1       0.00      0.00      0.00        11

    accuracy                           0.52        23
   macro avg       0.26      0.50      0.34        23
weighted avg       0.27      0.52      0.36        23

Confusion Matrix after date 2014:
[[12  0]
 [11  0]]
Weighted F1-score after date 2014: 0.35776397515527947

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.2841

Evaluation on date 2014: Weighted F1 = 0.3578

Evaluation on date 2015: Weighted F1 = 0.3012

Evaluation on date 2016: Weighted F1 = 0.4797

Evaluation on date 2017: Weighted F1 = 0.9934

Evaluation on date 2019: Weighted F1 = 0.4654

Evaluation on date 2020: Weighted F1 = 0.3600

=== Phase 3: Training/Fine-tuning on date: 2015 ===

Classification Report after date 2015:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.53      1.00      0.69         9

    accuracy                           0.53        17
   macro avg       0.26      0.50      0.35        17
weighted avg       0.28      0.53      0.37        17

Confusion Matrix after date 2015:
[[0 8]
 [0 9]]
Weighted F1-score after date 2015: 0.36651583710407243

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.3850

Evaluation on date 2014: Weighted F1 = 0.3095

Evaluation on date 2015: Weighted F1 = 0.3665

Evaluation on date 2016: Weighted F1 = 0.2058

Evaluation on date 2017: Weighted F1 = 0.0000

Evaluation on date 2019: Weighted F1 = 0.2163

Evaluation on date 2020: Weighted F1 = 0.3074

=== Phase 4: Training/Fine-tuning on date: 2016 ===

Classification Report after date 2016:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7861
           1       0.99      0.98      0.98      4743

    accuracy                           0.99     12604
   macro avg       0.99      0.99      0.99     12604
weighted avg       0.99      0.99      0.99     12604

Confusion Matrix after date 2016:
[[7801   60]
 [  93 4650]]
Weighted F1-score after date 2016: 0.987852521165446

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.3636

Evaluation on date 2014: Weighted F1 = 0.4953

Evaluation on date 2015: Weighted F1 = 0.4759

Evaluation on date 2016: Weighted F1 = 0.9879

Evaluation on date 2017: Weighted F1 = 0.9943

Evaluation on date 2019: Weighted F1 = 0.3129

Evaluation on date 2020: Weighted F1 = 0.4182

=== Phase 5: Training/Fine-tuning on date: 2017 ===

Classification Report after date 2017:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3318
           1       0.57      0.57      0.57        14

    accuracy                           1.00      3332
   macro avg       0.78      0.78      0.78      3332
weighted avg       1.00      1.00      1.00      3332

Confusion Matrix after date 2017:
[[3312    6]
 [   6    8]]
Weighted F1-score after date 2017: 0.9963985594237695

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.2606

Evaluation on date 2014: Weighted F1 = 0.6522

Evaluation on date 2015: Weighted F1 = 0.5193

Evaluation on date 2016: Weighted F1 = 0.9862

Evaluation on date 2017: Weighted F1 = 0.9964

Evaluation on date 2019: Weighted F1 = 0.3437

Evaluation on date 2020: Weighted F1 = 0.4657

=== Phase 6: Training/Fine-tuning on date: 2019 ===

Classification Report after date 2019:
              precision    recall  f1-score   support

           0       0.62      0.90      0.73        68
           1       0.46      0.14      0.21        43

    accuracy                           0.60       111
   macro avg       0.54      0.52      0.47       111
weighted avg       0.56      0.60      0.53       111

Confusion Matrix after date 2019:
[[61  7]
 [37  6]]
Weighted F1-score after date 2019: 0.5332449489075995

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.2841

Evaluation on date 2014: Weighted F1 = 0.3578

Evaluation on date 2015: Weighted F1 = 0.3012

Evaluation on date 2016: Weighted F1 = 0.9790

Evaluation on date 2017: Weighted F1 = 0.9951

Evaluation on date 2019: Weighted F1 = 0.5332

Evaluation on date 2020: Weighted F1 = 0.5040

=== Phase 7: Training/Fine-tuning on date: 2020 ===

Classification Report after date 2020:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1106
           1       0.98      0.97      0.97      1006

    accuracy                           0.98      2112
   macro avg       0.98      0.97      0.98      2112
weighted avg       0.98      0.98      0.98      2112

Confusion Matrix after date 2020:
[[1088   18]
 [  34  972]]
Weighted F1-score after date 2020: 0.975368512172596

--- Evaluation on all datasets ---

Evaluation on date 2011-2013: Weighted F1 = 0.3409

Evaluation on date 2014: Weighted F1 = 0.3734

Evaluation on date 2015: Weighted F1 = 0.4858

Evaluation on date 2016: Weighted F1 = 0.3143

Evaluation on date 2017: Weighted F1 = 0.2222

Evaluation on date 2019: Weighted F1 = 0.6029

Evaluation on date 2020: Weighted F1 = 0.9754

In [9]:
# ---------------
# Results summary
# ---------------

print("\n=== Results Summary ===")
for date, res in results.items():
    print(f"\nResults after training on date {date}:")
    for test_date, f1 in res.items():
        print(f"  Test on date {test_date}: Weighted F1 = {f1:.4f}")

=== Results Summary ===

Results after training on date 2011-2013:
  Test on date 2011-2013: Weighted F1 = 0.3850
  Test on date 2014: Weighted F1 = 0.3095
  Test on date 2015: Weighted F1 = 0.3665
  Test on date 2016: Weighted F1 = 0.2058
  Test on date 2017: Weighted F1 = 0.0000
  Test on date 2019: Weighted F1 = 0.2163
  Test on date 2020: Weighted F1 = 0.3074

Results after training on date 2014:
  Test on date 2011-2013: Weighted F1 = 0.2841
  Test on date 2014: Weighted F1 = 0.3578
  Test on date 2015: Weighted F1 = 0.3012
  Test on date 2016: Weighted F1 = 0.4797
  Test on date 2017: Weighted F1 = 0.9934
  Test on date 2019: Weighted F1 = 0.4654
  Test on date 2020: Weighted F1 = 0.3600

Results after training on date 2015:
  Test on date 2011-2013: Weighted F1 = 0.3850
  Test on date 2014: Weighted F1 = 0.3095
  Test on date 2015: Weighted F1 = 0.3665
  Test on date 2016: Weighted F1 = 0.2058
  Test on date 2017: Weighted F1 = 0.0000
  Test on date 2019: Weighted F1 = 0.2163
  Test on date 2020: Weighted F1 = 0.3074

Results after training on date 2016:
  Test on date 2011-2013: Weighted F1 = 0.3636
  Test on date 2014: Weighted F1 = 0.4953
  Test on date 2015: Weighted F1 = 0.4759
  Test on date 2016: Weighted F1 = 0.9879
  Test on date 2017: Weighted F1 = 0.9943
  Test on date 2019: Weighted F1 = 0.3129
  Test on date 2020: Weighted F1 = 0.4182

Results after training on date 2017:
  Test on date 2011-2013: Weighted F1 = 0.2606
  Test on date 2014: Weighted F1 = 0.6522
  Test on date 2015: Weighted F1 = 0.5193
  Test on date 2016: Weighted F1 = 0.9862
  Test on date 2017: Weighted F1 = 0.9964
  Test on date 2019: Weighted F1 = 0.3437
  Test on date 2020: Weighted F1 = 0.4657

Results after training on date 2019:
  Test on date 2011-2013: Weighted F1 = 0.2841
  Test on date 2014: Weighted F1 = 0.3578
  Test on date 2015: Weighted F1 = 0.3012
  Test on date 2016: Weighted F1 = 0.9790
  Test on date 2017: Weighted F1 = 0.9951
  Test on date 2019: Weighted F1 = 0.5332
  Test on date 2020: Weighted F1 = 0.5040

Results after training on date 2020:
  Test on date 2011-2013: Weighted F1 = 0.3409
  Test on date 2014: Weighted F1 = 0.3734
  Test on date 2015: Weighted F1 = 0.4858
  Test on date 2016: Weighted F1 = 0.3143
  Test on date 2017: Weighted F1 = 0.2222
  Test on date 2019: Weighted F1 = 0.6029
  Test on date 2020: Weighted F1 = 0.9754